added `preg_filter` return-type extension
phpstan/phpstan-src pull request #1024
Opened 2022-02-18 16:01 UTC by staabm

closes https://github.com/phpstan/phpstan/issues/6664

2022-02-18 16:02 UTC, staabm commented on src/Type/Php/ArrayRandFunctionReturnTypeExtension.php
> +		if ($argsCount < 1) {
drive-by cleanup

2022-02-23 08:43 UTC, ondrejmirtes requested changes

2022-02-23 08:43 UTC, ondrejmirtes commented on src/Type/Php/PregFilterFunctionReturnTypeExtension.php
> +			return $defaultReturn;
This branch isn't tested

2022-02-23 08:43 UTC, ondrejmirtes commented on src/Type/Php/PregFilterFunctionReturnTypeExtension.php
> +		return $defaultReturn;
This branch isn't tested

2022-03-02 09:10 UTC, merged

2022-03-02 12:24 UTC, arnaud-lb commented
Thank you @staabm !