Retain accessory string types in generics
phpstan/phpstan-src pull request #1096
Opened 2022-03-21 16:01 UTC by rvanvelzen

Seems to fix phpstan/phpstan#6301. Inferring template types on intersection types is problematic because the bound type may not necessarily be a super type of all sub types of the passed intersection type.

2022-03-21 16:17 UTC, ondrejmirtes requested changes
Otherwise 👍

2022-03-21 16:17 UTC, ondrejmirtes commented on tests/PHPStan/Analyser/NodeScopeResolverTest.php
> +		require_once __DIR__ . '/../Rules/Generics/data/bug-6301.php';
No need to require it. If it failed locally for you, you forgot to run `composer dump` before running the tests :)

2022-03-22 07:54 UTC, ondrejmirtes approved these changes

2022-03-22 07:54 UTC, merged

2022-03-22 07:54 UTC, ondrejmirtes commented
Thank you!

2022-03-22 08:35 UTC, ondrejmirtes commented
BTW @rvanvelzen Can you please send a regression test for https://github.com/phpstan/phpstan-src/pull/1096 ? 

NodeScopeResolverTest case that checks the type of `$subject` before `return` is fine. And of course make sure it fails when your fix is reverted :) Thanks.

2022-03-22 08:35 UTC, ondrejmirtes commented
Sorry, correct link https://github.com/phpstan/phpstan/issues/3951

2022-03-22 08:37 UTC, ondrejmirtes commented
Oh, there are even more: https://github.com/phpstan/phpstan/issues/6845 and https://github.com/phpstan/phpstan/issues/5336

2022-03-22 08:38 UTC, staabm commented
Fyi, A regression test for https://github.com/phpstan/phpstan/issues/5336
Was already submitted in https://github.com/phpstan/phpstan-src/pull/1100