Fix huge union types result from "+"-array-merge operation
phpstan/phpstan-src pull request #1141
Opened 2022-03-29 14:45 UTC by staabm

with the fix we apply the limit already used in `ConstantArrayTypeBuilder` also to the merge-process when analyzing arrays beeing merged by the `+`-operator.

without the fix, the provided testcase runs 2-4 minutes. with the fix it runs in 3-5 seconds.

closes https://github.com/phpstan/phpstan/issues/6936

2022-03-29 14:49 UTC, ondrejmirtes requested changes
Also please demonstrate in NodeScopeResolverTest what happens if we go right under and right over the limit. Thanks.

2022-03-29 14:49 UTC, ondrejmirtes commented on src/Analyser/MutatingScope.php
> +					&& (count($leftConstantArrays) + count($rightConstantArrays) < ConstantArrayTypeBuilder::ARRAY_COUNT_LIMIT)) {
Please save the counts into variables and reuse the variable so that it doesn't have to be counted multiple times.

2022-03-29 15:58 UTC, staabm commented
I tried for more then an hour, but it seems I am not able to come up with a proper NodeScopeResolverTest for it.

either my fix only works by accident, or I am really not able to create the test... I don't know right now.

2022-03-30 08:11 UTC, staabm commented
finally found a test-case which works locally. lets see what CI is thinking about it

2022-03-30 13:40 UTC, merged

2022-03-30 13:41 UTC, ondrejmirtes commented
Perfect, thank you.