Int mask
phpstan/phpstan-src pull request #1166
Opened 2022-04-02 12:46 UTC by rvanvelzen

2022-04-02 12:48 UTC, rvanvelzen commented
I'm not convinced 0 should be part of the union by default, but it's easy enough to add. Psalm does include it, so for parity it might be best to include it.

2022-04-02 13:03 UTC, ondrejmirtes commented
Yeah, let's include `0`. It's questionable, in some cases people want `0` and in some cases they don't, but we don't know which is which so let's do the wider and less annoying thing here.

2022-04-02 13:05 UTC, ondrejmirtes requested changes

2022-04-02 13:05 UTC, ondrejmirtes commented on src/PhpDoc/TypeNodeResolver.php
> +					$values[] = $value | $int;
One idea for improvement. If the generated integer list is continuous, we could return IntegerRangeType instead.

2022-04-02 13:05 UTC, ondrejmirtes commented
Also please submit documentation for these types to https://phpstan.org/writing-php-code/phpdoc-types - there's a link to edit the page at the bottom.

2022-04-04 16:23 UTC, merged

2022-04-04 16:24 UTC, ondrejmirtes commented
Perfect, thank you!

Two ideas:

1) Test for a scenario when a value that's not power-of-2 (like 3) is part of the values.
2) when a non-integer is mentioned in the PHPDoc, the resulting type should be ErrorType. That will get picked up as unresolvable type by a rule.

2022-04-04 17:05 UTC, Seldaek commented
Great, thanks!