Trigger errors for unresolvable parameters
phpstan/phpstan-src pull request #1319
Opened 2022-05-16 14:14 UTC by rvanvelzen

2022-05-16 14:21 UTC, ondrejmirtes requested changes

2022-05-16 14:21 UTC, ondrejmirtes commented on src/Rules/FunctionCallParametersCheck.php
> +			if ($this->unresolvableTypeHelper->containsUnresolvableType($parameterType)) {
These contributions make me drool! So good 😊 But it should be reported only with bleedingEdge enabled (by adding new featureToggles parameter), who knows what's it gonna unleash in real codebases 😊

2022-05-17 06:54 UTC, rvanvelzen commented
The one test failure is a BC break for a non-`@api` method call. Should I make the message optional, or is the breakage acceptable?

2022-05-17 07:03 UTC, canvural commented
@rvanvelzen I think it's fine. It's my fault to use non-`@api` calls 😄  I'll fix it there.

2022-05-17 07:07 UTC, ondrejmirtes commented
@canvural Maybe I suggested to you myself to use FunctionCallParametersCheck so I'm sorry about it :) There should be a way in Larastan to do it nicer, just an idea: allow custom rule developer to invoke their own virtual nodes. You could invoke a custom `FuncCall` node and the rules in PHPStan would pick it up themselves.

But for now, feel free to prepare a new Larastan release that requires PHPStan ^1.7 (after this PR is merged), we can then coordinate the release together :)

2022-05-17 07:08 UTC, ondrejmirtes commented
Or pass the extra argument to FunctionCallParametersCheck, ignore PHPStan error for now, release it (and not change the PHPStan requirements), and clean it up after 1.7 is releaased :)

2022-05-17 07:09 UTC, ondrejmirtes commented
@rvanvelzen Just one more thing - have you looked into the failures before the new check was behind a feature toggle?

* https://github.com/phpstan/phpstan-src/runs/6453862910?check_suite_focus=true
* https://github.com/phpstan/phpstan-src/runs/6453863040?check_suite_focus=true
* https://github.com/phpstan/phpstan-src/runs/6453863215?check_suite_focus=true
* https://github.com/phpstan/phpstan-src/runs/6453863498?check_suite_focus=true

It'd be good to fix them now since it's a valuable piece of feedback about the new check :)

2022-05-17 07:24 UTC, rvanvelzen commented
@ondrejmirtes yeah, I fixed most of them in f3c5928. There's one left that I'll try to fix.

2022-05-17 09:47 UTC, merged

2022-05-17 09:48 UTC, ondrejmirtes commented
Thank you!

2022-05-17 11:08 UTC, ondrejmirtes commented
I went the optional way as that avoids all of the headaches: https://github.com/phpstan/phpstan-src/commit/a114a3f1c4158723786aadaf67d9abcf6b0e0b88