NodeScopeResolver: call nodeCallback for all attribute-related nodes
phpstan/phpstan-src pull request #1333
Opened 2022-05-20 07:35 UTC by janedbal

Resolves https://github.com/phpstan/phpstan/issues/7071

2022-05-20 08:25 UTC, staabm commented
should contain a regression test for the issue being fixed

2022-05-20 11:19 UTC, janedbal commented
Tests added

2022-05-20 11:22 UTC, ondrejmirtes commented
Please fix the build. Lint can be fixed by adding `// lint >= 7.4` comments, tests should be fixed by skipping on unsupported PHP versions. Thanks.

2022-05-20 15:04 UTC, ondrejmirtes requested changes

2022-05-20 15:04 UTC, ondrejmirtes commented on src/Analyser/NodeScopeResolver.php
> +			$this->processAttributeGroups($stmt->attrGroups, $scope, $nodeCallback);
You're calling this with the wrong scope. You need `$classScope` here.

2022-05-23 07:21 UTC, ondrejmirtes commented
FYI this will conflict with your PR https://github.com/phpstan/phpstan-src/pull/1338, please update your code too.

2022-05-27 14:36 UTC, merged

2022-05-27 14:36 UTC, ondrejmirtes commented
Thank you!