Use explicit mixed for global array variables
phpstan/phpstan-src pull request #1411
Opened 2022-06-10 09:12 UTC by herndlm

Refs: https://github.com/phpstan/phpstan/discussions/7450

well, let's see how much this will break..

2022-06-10 09:13 UTC, ondrejmirtes commented
Definitely needs to be a bleedingEdge tag :) Don't forget to update LazyScopeFactory + DirectScopeFactory.

2022-06-11 06:22 UTC, ondrejmirtes requested changes

2022-06-11 06:22 UTC, ondrejmirtes commented on tests/PHPStan/Rules/Functions/CallToFunctionParametersRuleTest.php
> +		$this->checkExplicitMixed = true;
Please test it with `false` too.

2022-06-13 08:15 UTC, merged

2022-06-13 08:15 UTC, ondrejmirtes commented
Perfect, thank you!

2022-06-21 08:44 UTC, gnutix commented
Hey there. Just a question: does this change means the developers should always use a `@var` to describe the content of the global array they are using, everywhere they do so ?

2022-06-21 12:06 UTC, ondrejmirtes commented
Developers should never use `@var`, especially not on an untrusted user input 😊

The right approach now is cuyz/valinor, or azjezz/psl.

2022-06-23 06:49 UTC, herndlm commented
> How exactly do you do that in this scenario ? Storing the value of the global array you want to use into a variable and using `@var` on the variable, or doing `is_*()` (string, numeric, ...) kind of checks on the value of the global array before using it ?

yeah, basically just https://phpstan.org/writing-php-code/narrowing-types. We just had some simple primitive type fields/vars from $_POST, just as the playground-snippet from the linked discussion.

for more complex array shapes I would definitely also try to use what Ondrej suggested in the previous comment. Never used those libs, but they are on my list :)