added SscanfFunctionDynamicReturnTypeExtension return type extension
phpstan/phpstan-src pull request #1434
Opened 2022-06-17 13:52 UTC by staabm

2022-06-17 13:59 UTC, staabm commented on tests/PHPStan/Analyser/data/sscanf.php
> +	assertType('array{string}|null', sscanf($s, '%c'));
https://3v4l.org/HgMjg

2022-06-17 14:01 UTC, staabm commented on tests/PHPStan/Analyser/data/sscanf.php
> +	assertType('array|null', sscanf($s, $s));
the 2 test-cases which existed before.. now with just a `string` format, because otherwise we would not get the same results

2022-06-17 14:08 UTC, staabm commented
built errors seem unrelated

2022-06-17 15:06 UTC, ondrejmirtes requested changes

2022-06-17 15:06 UTC, ondrejmirtes commented on tests/PHPStan/Analyser/data/sscanf.php
> +	assertType('array|null', sscanf($s, $s));
Please change assertions of the existing `sscanf('20-20', '%d-%d', $first, $second)` test and add `sscanf($s, $s, $first, $second)` as a separate one.

2022-06-17 16:35 UTC, staabm commented on tests/PHPStan/Analyser/data/sscanf.php
> +	assertType('array|null', sscanf($s, $s));
done

2022-06-17 21:25 UTC, merged

2022-06-17 21:25 UTC, ondrejmirtes commented
Thank you!

2022-08-09 13:16 UTC, Alkarex commented
Maybe a regression https://github.com/phpstan/phpstan/issues/7764