Reindex constant arrays via `shuffle`
phpstan/phpstan-src pull request #1438
Opened 2022-06-17 19:01 UTC by herndlm

Closes https://github.com/phpstan/phpstan/issues/6138

While this is an improvement I'm not a 100% happy with it, because the constant array still dictates the same order of values after `shuffle`, which is not correct. But generalizing it to a normal array would loose the key order I presume? Better ideas?

2022-06-17 21:22 UTC, ondrejmirtes commented
I'd say the array should be general (`ArrayType`) after shuffle because the key => value type association is no longer maintained - ConstantArrayType is no longer correct.

2022-06-17 22:39 UTC, herndlm commented
I had the same thought but then we loose the keys I guess. But OK, I'll look into that tomorrow's

2022-06-30 13:07 UTC, herndlm commented
"tomorrow" = ~2 weeks in the parallel universe I was living :)
should be adapted. `shuffle` leads now to a generic array and re-indexes the keys. The only thing that was lost is the order of the keys which is always `0, 1, 2, ..` but I guess we can't retain them at the moment.

2022-06-30 14:26 UTC, ondrejmirtes requested changes

2022-06-30 14:26 UTC, ondrejmirtes commented on tests/PHPStan/Analyser/data/bug-6138.php
> +shuffle( $unordered );
Please also assert:

1) Shuffle of an empty array
2) Shuffle of an array we don't know that's empty or not
3) The shuffled arrays directly next to their `array_keys` too.

2022-06-30 18:50 UTC, herndlm commented on tests/PHPStan/Analyser/data/bug-6138.php
> +shuffle( $unordered );
good thinking with the empty (constant) array, currently there were a lot of `*Never*` types..
I adapted it and I think I tested all of this in a dedicated `shuffle` test file.

2022-06-30 18:58 UTC, herndlm commented
Not a 100% happy with this, but I can't come up with something better. Basically something like a shuffled list / shuffled constant array would be needed, but that feels very much like an edge case :)

2022-07-01 12:00 UTC, merged

2022-07-01 12:00 UTC, ondrejmirtes commented
Thank you.