Type a ranged value for filter_var(FILTER_VALIDATE_INT)
phpstan/phpstan-src pull request #1443
Opened 2022-06-19 14:48 UTC by zonuexe

closes https://github.com/phpstan/phpstan/issues/7494

2022-06-19 16:42 UTC, zonuexe commented on src/Type/Php/FilterVarDynamicReturnTypeExtension.php
> +			// $this->getConstant('FILTER_VALIDATE_FLOAT') => ['min_range', 'max_range'],
I don't plan to use it immediately, but it is possible to make `FloatRangeType` with `-INF <= float <= INF`.

2022-06-20 07:25 UTC, ondrejmirtes requested changes

2022-06-20 07:25 UTC, ondrejmirtes commented on src/Type/Php/FilterVarDynamicReturnTypeExtension.php
> +			&& $type instanceof StringType
`$type->isString()->yes()`

2022-06-20 07:25 UTC, ondrejmirtes commented on src/Type/Php/FilterVarDynamicReturnTypeExtension.php
> +			$type = new IntersectionType([$type, new AccessoryNonEmptyStringType()]);
`TypeCombinator::intersect()` instead please

2022-06-20 07:25 UTC, ondrejmirtes commented on src/Type/Php/FilterVarDynamicReturnTypeExtension.php
> +			$type = new UnionType([$type, $otherTypes['default']]);
`TypeCombinator::union()` please

2022-06-20 07:25 UTC, ondrejmirtes commented on src/Type/Php/FilterVarDynamicReturnTypeExtension.php
> +			$otherTypes['range'] = new IntegerRangeType($min, $max);
`IntegerRangeType::fromInterval()` please

2022-06-22 11:53 UTC, zonuexe commented on src/Type/Php/FilterVarDynamicReturnTypeExtension.php
> +			$type = new IntersectionType([$type, new AccessoryNonEmptyStringType()]);
Fixed https://github.com/phpstan/phpstan-src/pull/1443/commits/fec2ef66a70218522bf5954338b3aa84dd8b3a20

2022-06-22 11:54 UTC, zonuexe commented on src/Type/Php/FilterVarDynamicReturnTypeExtension.php
> +			$otherTypes['range'] = new IntegerRangeType($min, $max);
Fixed https://github.com/phpstan/phpstan-src/pull/1443/commits/09ae19764dab721c0ff26ef34ee363d089928316

2022-06-22 11:54 UTC, zonuexe commented on src/Type/Php/FilterVarDynamicReturnTypeExtension.php
> +			&& $type instanceof StringType
Fixed https://github.com/phpstan/phpstan-src/pull/1443/commits/e301f6dbaea2eeed2a740d862c37602b940387d8

2022-06-22 13:07 UTC, merged

2022-06-22 13:07 UTC, ondrejmirtes commented
Thank you!