Inherit `@immutable` phpdoc
phpstan/phpstan-src pull request #1489
Opened 2022-07-01 13:50 UTC by herndlm

Closes https://github.com/phpstan/phpstan/issues/7506

2022-07-01 14:20 UTC, BackEndTea commented
Should this also work for interfaces? E.g. declare @immutable on the interface means all implementations are immutable

2022-07-01 14:29 UTC, herndlm commented
> Should this also work for interfaces? E.g. declare @immutable on the interface means all implementations are immutable

I might be missing something, but I think it should be fine because immutable currently only makes all props readonly and interfaces don't have props, right?
Methods are by default considered to be pure AFAIK and therefore this is not messed with via immutable yet.

2022-07-10 12:36 UTC, ondrejmirtes requested changes

2022-07-10 12:36 UTC, ondrejmirtes commented on src/Reflection/ClassReflection.php
> +		if ($parentClass !== null && !$this->isImmutable) {
Please move everything into the `if ($this->isImmutable === null) {` code block - the whole logic of this method is that the property caches the result. The computation should be done inside that code block.

2022-07-10 14:07 UTC, merged

2022-07-10 14:07 UTC, ondrejmirtes commented
Thank you!