Fix Identical type specification of constant types
phpstan/phpstan-src pull request #1493
Opened 2022-07-02 20:19 UTC by herndlm

Closes https://github.com/phpstan/phpstan/issues/7257

This was not working correctly because e.g. a `ConstantArrayType` with optional keys that leads to a `BooleanType` (instead of a `ConstantBooleanType` if `toBoolean` is called) cannot be safely used to strictly specify the other (left or right) type in the Identical comparison.

The problem with the linked issue was that it would basically cancel out the types in a falsey scope (the right side of the `||` for e.g. `$sorted` leading to a `NeverType`), see https://phpstan.org/r/f560aac6-602f-45a0-8115-bb94f7142f79. Which explains why it works if only truthy scopes (via variable assignments) work around that.

2022-07-02 20:45 UTC, herndlm commented
wait no, `toBoolean` is not the right thing to fix this..

2022-07-10 12:42 UTC, ondrejmirtes requested changes

2022-07-10 12:42 UTC, ondrejmirtes commented on src/Analyser/TypeSpecifier.php
> +				|| $exprLeftType instanceof EnumCaseObjectType
Please disambiguate `&&`/`||` operator priority with parentheses :)

2022-07-10 12:42 UTC, ondrejmirtes commented on src/Analyser/TypeSpecifier.php
> +				|| $exprRightType instanceof EnumCaseObjectType
Please disambiguate `&&`/`||` operator priority with parentheses :)

2022-07-10 13:08 UTC, merged

2022-07-10 13:08 UTC, ondrejmirtes commented
Thank you very much!

2022-07-10 14:13 UTC, ondrejmirtes commented
There are bunch of code examples in current issues where the results changed because of this PR:

* https://github.com/phpstan/phpstan/issues/6781
* https://github.com/phpstan/phpstan/issues/6647
* https://github.com/phpstan/phpstan/issues/5896
* https://github.com/phpstan/phpstan/issues/5474
* https://github.com/phpstan/phpstan/issues/6000

Can you please go through them and see:

* If it's A) fixing a bug or B) introducing a new bug
* A): please send a regression test :)
* B): please reproduce the problem in a test and fix the test :)

Thank you very much!

2022-07-10 15:17 UTC, herndlm commented
Looking good, do you have preferences in the regressions? All in one PR/commit OK? Looks like I'll also have to create two tests for an issue or two

2022-07-10 16:36 UTC, ondrejmirtes commented
Each closed issue should have a separate test case, meaning `testBugXyz` for rule test cases, or separate file in NodeScopeResolverTest :) They can be a single commit "Regression tests".