Added stub files and tests for array_* functions.
phpstan/phpstan-src pull request #1571
Opened 2022-07-30 14:16 UTC by mad-briller

closes https://github.com/phpstan/phpstan/issues/7707

functions stubbed:

array_diff_uassoc
array_diff_ukey
array_intersect_uassoc
array_intersect_ukey
array_udiff_assoc
array_udiff_uassoc
array_uintersect_assoc
array_uintersect_uassoc
array_uintersect

whilst adding these, phpstan warned because i didn't add array iterable types for the returns so i've specified them in the stubs, however i noticed [this return type extension plugin](https://github.com/phpstan/phpstan-src/blob/1.8.x/src/Type/Php/ArgumentBasedFunctionReturnTypeExtension.php#L16) which seems to be overriding them anyway, if theres something i should do instead let me know 
should i remove the stubbed methods from the extension?

2022-07-30 16:09 UTC, ondrejmirtes requested changes
The TK templates should have `array-key` bounds instead of mixed.

2022-07-30 16:23 UTC, mad-briller commented
i tried that but it seemed to break the templating by using `array-key` or even `int|string` and i couldn't quite figure out why  

when using `array-key` it reverted to showing errors like this:
```
+30: Parameter #3 $data_comp_func of function array_diff_uassoc expects callable(mixed, mixed): int, Closure(string, string): int<-1, 1> given.
```

2022-07-30 20:28 UTC, ondrejmirtes commented
Please push the stubs with `array-key` and then try to figure out why these errors are reported by debugging the codebase :) Thanks.

2022-09-01 21:34 UTC, ondrejmirtes commented
Feel free to open a new PR if you decide to finish it, thank you :)

2022-09-01 21:34 UTC, closed without merging