added asserts to regression tests
phpstan/phpstan-src pull request #1598
Opened 2022-08-06 14:54 UTC by staabm

as requested in https://github.com/phpstan/phpstan-src/pull/1596#pullrequestreview-1064299237

2022-08-06 14:57 UTC, staabm commented on tests/PHPStan/Analyser/data/bug-7417.php
> +	assertType('non-empty-array', $extensions); // could be more precise
room for improvement

2022-08-06 20:24 UTC, ondrejmirtes requested changes
You're adding the same classes that already exist in different files. This can cause big headaches later.

Please just reuse the files from tests/PHPStan/Rules and add these assertType calls in them. Thanks.

2022-08-07 06:22 UTC, staabm commented
done 👍

2022-08-07 06:43 UTC, merged

2022-08-07 06:43 UTC, ondrejmirtes commented
Thank you!