Feature/psalm readonly allow private mutation
phpstan/phpstan-src pull request #1610
Opened 2022-08-11 16:37 UTC by zonuexe

resolve https://github.com/phpstan/phpstan/issues/7778, refs https://github.com/phpstan/phpstan-src/pull/1609

2022-08-11 16:48 UTC, zonuexe commented
`ReadOnlyByPhpDocPropertyAssignRuleTest` alone will pass with e2d9db8fc29efb52a847de6df704b7a540c0331e patch, but you probably need to rethink how `ResolvedPhpDocBlock::$phpDocNode` is initialized.

2022-09-13 10:40 UTC, zonuexe commented on src/PhpDoc/ResolvedPhpDocBlock.php
> +		}
```
Error: Property PHPStan\PhpDoc\ResolvedPhpDocBlock::$phpDocNode (PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode) in isset() is not nullable.
Error: Property PHPStan\PhpDoc\ResolvedPhpDocBlock::$phpDocNodeResolver (PHPStan\PhpDoc\PhpDocNodeResolver) in isset() is not nullable.
 ------ ------------------------------------------------------------------ 
  Line   src/PhpDoc/ResolvedPhpDocBlock.php                                
 ------ ------------------------------------------------------------------ 
  225    Property PHPStan\PhpDoc\ResolvedPhpDocBlock::$phpDocNode          
         (PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode) in isset() is not    
         nullable.                                                         
  [24](https://github.com/phpstan/phpstan-src/actions/runs/3044344145/jobs/4904629542#step:11:25)3    Property PHPStan\PhpDoc\ResolvedPhpDocBlock::$phpDocNodeResolver  
         (PHPStan\PhpDoc\PhpDocNodeResolver) in isset() is not nullable.   
 ------ ------------------------------------------------------------------
```

https://github.com/phpstan/phpstan-src/actions/runs/3044344145/jobs/4904629542#step:11:9

2022-09-13 10:42 UTC, zonuexe commented
@ondrejmirtes Could you please review this PR?

2022-09-24 16:19 UTC, ondrejmirtes requested changes

2022-09-24 16:19 UTC, ondrejmirtes commented on src/PhpDoc/ResolvedPhpDocBlock.php
> +			$result->phpDocNodeResolver = $this->phpDocNodeResolver;
Hi, you¨re adding a simple boolean value which there are already many present. These changes to phpDocNode and phpDocNodeResolver are not required to make this work, and cause these build failures.

If the PR doesn't work without these changes, please observe how different boolean values are handled here, it shouldn't be hard to make them work.

2022-09-25 07:38 UTC, zonuexe commented
Sorry, I accidentally submitted a re-review. Ignore it for once.

2022-09-27 12:42 UTC, ondrejmirtes commented
I've updated the PR with the correct fix.

2022-09-27 12:42 UTC, ondrejmirtes approved these changes

2022-09-27 12:44 UTC, merged

2022-09-27 12:44 UTC, ondrejmirtes commented
Thank you.