implement loose comparison
phpstan/phpstan-src pull request #1640
Opened 2022-08-22 19:32 UTC by staabm

the tests added with his PR represent the comparison table from https://www.php.net/manual/en/types.comparisons.php inspired by https://github.com/phpstan/phpstan-src/pull/1602#discussion_r940628091

the more time I spent while working with loose comparisons, the more I realize how crazy those compare rules actually are.

2022-08-23 14:57 UTC, ondrejmirtes commented
I think loose comparisons should be implemented via a new method like `Type::looseCompare(Type $type): BooleanType`. That will allow us to answer all possible situations.

2022-08-23 18:29 UTC, staabm commented
I see. 

This implies we also need to implement `Type::strictCompare($type): BooleanType` in the same PR, because atm `InitializerExprTypeResolver->resolveEqualType()` is calling into `InitializerExprTypeResolver->resolveIdenticalType()`.

moving the code arround will touch stuff already changed in https://github.com/phpstan/phpstan-src/pull/1634, so I will wait until #1634 is merged before starting the refactoring.

2022-08-23 18:36 UTC, ondrejmirtes commented
Strict compare method isn't needed, that's already basically isSuperTypeOf, if you see how Identical is implemented in MutatingScope. I don't know of any bug that would suggest lack of something in this area.

2022-08-23 20:30 UTC, staabm reviewed
added the new type method.

looked into the test errors and as far as I can say, these look like unrelated to this PR.

2022-08-23 20:30 UTC, staabm commented on src/Reflection/InitializerExprTypeResolver.php
>  	public function resolveEqualType(Type $leftType, Type $rightType): BooleanType
if desired, `resolveEqualType` could be inlined as it is now a single line method

2022-08-24 09:16 UTC, ondrejmirtes requested changes
The implementations of `looseCompare` are going to be much more complicated, also i don't think there's such a thing as `NonLooseComparableTrait`. Every type can be put in `==`...

2022-08-24 13:54 UTC, staabm commented
ok, just to get it right: I need to implement/test all types compared against all other types (+itself), right?

2022-08-24 14:07 UTC, ondrejmirtes commented
Yes. It's PITA for sure 😊

2022-08-24 14:12 UTC, ondrejmirtes commented
If you're going to pursue this, submit an implementation in one or two types first before fully diving in, to make sure we're on the same page. For example `StringType::looseCompare()` has to account for:

* Any UnionType
* Any IntersectionType
* Against any object it's false
* Looks like against any array it's also false
* To correctly answer when it's `non-empty-string`, `non-falsy-string`, `numeric-string`...

The UnionType/IntersectionType is probably going to be solved similarly as `accepts()/isAcceptedBy()` / `isSuperTypeOf()/isSubTypeOf()`, meaning we're gonna need another method counterpart in `CompoundType`.

2022-08-25 06:15 UTC, staabm commented
ok thanks. before bringing up the first type, I will give other open PRs of mine some love, which are not blocked by external changes - so we can clean up the pull request queue first

2022-10-16 10:52 UTC, ondrejmirtes commented
Hi, I'm cleaning up old and stale PRs. Please send a new PR if you're still interested, thanks.

2022-10-16 10:52 UTC, closed without merging