Avoid benevolent union behaviour for more type methods
phpstan/phpstan-src pull request #1644
Opened 2022-08-23 14:52 UTC by herndlm

I mostly want to see what happens. Tbh this is based on a gut feeling than any real data. E.g. `isIterable` is still benevolent, otherwise trying to iterate over `(array|null)` fails which results only in a warning. On the other hand trying to use `(callable|null)` as callable would be a fatal error in case it is null. Same for `clone`.

This would "fix" `isString` checks IMO but it very much depends on the point of view I guess.

2022-08-23 15:20 UTC, herndlm commented
the 8 failures so far seem to be unrelated. a couple of weird CI temp errors apparently as well, maybe this should be force-pushed / re-triggered later. I don't want to stress it even more now

2022-08-23 15:23 UTC, ondrejmirtes commented
I'm sorry about the CI errors on 1.8.x. I'm working hard to remove these errors, they will get resolved before 1.8.3 is tagged.

2022-08-24 16:14 UTC, ondrejmirtes commented
I'd be happy to try this out (merge it) given some tests. Plain old unit tests in BenevolentUnionTypeTest (it might not exist yet) would be fine.

2022-08-24 20:24 UTC, ondrejmirtes requested changes
I disagree with the can/has changes, only is* behaviour should be changed.

2022-08-24 20:56 UTC, herndlm commented
> I disagree with the can/has changes, only is* behaviour should be changed.

fair point, the idea was that e.g. calling methods on null would lead to a fatal error. but same thing for calling that on stdClass, so good with me.

The only deviations are now only `isIterable` and `isIterableOnce`. Unfortunately making them stricter too starts reporting a new error. I'll push that commit though to check if it influences more.

The tests added so far are really simple and stupid and mostly copy/paste as you can see, but maybe they help for future fixes or so.

2022-08-25 12:47 UTC, merged

2022-08-25 12:47 UTC, ondrejmirtes commented
Thank you!