encoding functions returns non-empty-string
phpstan/phpstan-src pull request #1664
Opened 2022-08-30 09:49 UTC by staabm

analog https://github.com/vimeo/psalm/pull/8431

fixes https://phpstan.org/r/3a8a8430-1d4c-4bb9-99a8-f3838932f1e6

2022-08-31 07:18 UTC, staabm commented
the error in composer is valid and it was there before this PR. 

since the error message changed because generics are involved now, the already existing ignore-line no longer mutes it

https://github.com/ondrejmirtes/composer/blob/acef69614d5c54def3418d3964749b49923200b2/phpstan/baseline-8.1.neon#L278-L281

2022-09-01 09:30 UTC, ondrejmirtes requested changes

2022-09-01 09:30 UTC, ondrejmirtes commented on stubs/core.stub
> + * @return (T is non-empty-string ? non-empty-string : string)
You don't need generics for this, `($string is non-empty-string ? non-empty-string : string)` should work just as well. Please edit all of these fuctions.

2022-09-01 09:40 UTC, staabm commented on stubs/core.stub
> + * @return (T is non-empty-string ? non-empty-string : string)
good catch, fixed.

2022-09-01 09:45 UTC, merged

2022-09-01 09:45 UTC, ondrejmirtes commented
Thank you!