accept generic class string as literal string
phpstan/phpstan-src pull request #1692
Opened 2022-09-04 15:46 UTC by staabm

closes https://github.com/phpstan/phpstan/issues/7823

2022-09-04 16:20 UTC, ondrejmirtes commented
I disagree with this fix. class-string isn't always literal string.
Rather than that, `$x::class` should be an intersection with literal-string. You can implement that in MutatingScope::resolveType() and also verify that in NodeScopeResolverTest.

2022-09-05 08:29 UTC, VincentLanglet commented
> I disagree with this fix. class-string isn't always literal string.

@craigfrancis didn't give an example of class-string which are not literal-string in https://github.com/phpstan/phpstan-doctrine/issues/332#issuecomment-1134878945

But I think we should follow the way it's handled by psalm
https://psalm.dev/r/16085bfd30

2022-09-05 08:34 UTC, ondrejmirtes commented
```php
// $s is string
if (class_exists($s)) {
    // should $s suddenly be a literal-string?
}
```

2022-09-05 09:07 UTC, craigfrancis commented
[I’m out atm, and using phone, will try to check properly later]

The source of the variable has to be a literal, so if you got it from `example::class`, that’s fine… but if you’re checking the value contains a string that happens to match a class name (e.g. ‘class_exists()’), that doesn’t flip the variable to being a literal.

2022-09-05 09:08 UTC, ondrejmirtes commented
That's what I thought, so this PR has to be fixed with my suggestion. Thank you.

2022-09-05 16:10 UTC, staabm commented
thanks for the input guys. I just committed an update.

2022-09-05 20:36 UTC, staabm commented
The spurious out of memory error could also be observed on other PRs. I don‘t think it is related to the actual change

2022-09-06 09:12 UTC, rvanvelzen commented on src/Reflection/InitializerExprTypeResolver.php
> +							$stringType = new ConstantStringType($reflection->getName(), true);
`ConstantStringType` is already considered to be a literal string, so intersecting with `AccessoryLiteralStringType` will just remove the `AccessoryLiteralStringType` again.

2022-09-06 13:00 UTC, staabm commented on src/Reflection/InitializerExprTypeResolver.php
> +							$stringType = new ConstantStringType($reflection->getName(), true);
great catch! fixed

2022-09-06 14:51 UTC, ondrejmirtes requested changes
I'd say that the ifs above should also be covered by this PR. Basically any `$obj::class` is a literal-string.

So with `$obj::class` and `$obj` being EnumCaseObjectType, it should also be literal-string. And with `$type instanceof TemplateType && !$type instanceof TypeWithClassName` that should work too.

2022-09-07 17:30 UTC, staabm commented
adjusted per feedback.

I am wondering whether a `object`  typed parameter on which `::class` is appended should also be considered literal?

2022-09-07 17:53 UTC, ondrejmirtes commented
Of course :)

2022-09-20 15:36 UTC, ondrejmirtes commented
Please rebase and solve the conflict, I'll merge it then.

2022-09-20 15:49 UTC, merged

2022-09-20 15:49 UTC, ondrejmirtes commented
Thank you!