Introduce ArrayType traits
phpstan/phpstan-src pull request #1715
Opened 2022-09-09 11:41 UTC by herndlm

After thinking a bit about more array type cleanups, I thought this might be a good idea and precondition for both https://github.com/phpstan/phpstan-src/pull/1684 and https://github.com/phpstan/phpstan-src/pull/1687

Next, I'd update those 2 PRs, which should make their diff way smaller.

2022-09-09 11:55 UTC, herndlm commented
the failing tests are unrelated. the 2 that are expected and 2 segfaults / mingw errors on windows that are unexpected (to me) but I saw in my other PR too.

2022-10-05 08:06 UTC, ondrejmirtes requested changes
It'd probably make sense to base it on top of 1.9.x and put `isList` in there too :) Thank you.

2022-10-05 08:37 UTC, herndlm commented
> It'd probably make sense to base it on top of 1.9.x and put `isList` in there too :) Thank you.

right call you made there to save you from conflicts hehe
![Uploading image.png…]()

2022-10-05 08:37 UTC, herndlm commented
> It'd probably make sense to base it on top of 1.9.x and put `isList` in there too :) Thank you.

right call you made there to save you from conflicts hehe
![image](https://user-images.githubusercontent.com/5738896/194017820-3688c760-702d-4d03-91a5-fdbb9c0dddd3.png)

2022-10-05 09:11 UTC, herndlm commented on tests/PHPStan/Analyser/data/bug-8015.php
> +				assertType('list<string>', $config['things']);
I went through the diff multiple times now and still have no clue why this would change. anybody any ideas?

2022-10-05 09:57 UTC, herndlm commented on tests/PHPStan/Analyser/data/bug-8015.php
> +				assertType('list<string>', $config['things']);
-> https://github.com/phpstan/phpstan-src/pull/1796

2022-10-05 13:01 UTC, merged

2022-10-05 13:01 UTC, ondrejmirtes commented
Thank you!