more precise $argc, $argv global var type
phpstan/phpstan-src pull request #1718
Opened 2022-09-10 06:21 UTC by staabm

2022-09-10 06:23 UTC, staabm commented on tests/PHPStan/Analyser/data/cli-globals.php
> +	\PHPStan\Testing\assertType('mixed', $argv); // should be non-empty-array<int, string>
tried several things, but in the end wasn't able to identify this variable-scope.

therefore left it `mixed` for now

2022-09-10 06:26 UTC, staabm commented on tests/PHPStan/Analyser/data/cli-globals.php
> +\PHPStan\Testing\assertType('non-empty-array<int, string>', $argv);
$argc/$argv always count/contain the program name you pass `php test.php`, so actually you never have a empty type here.

2022-09-20 15:39 UTC, ondrejmirtes requested changes
Please also test if these variables are locally created by the user and contain a different type.

2022-09-20 15:39 UTC, ondrejmirtes commented on tests/PHPStan/Analyser/data/cli-globals.php
> +	\PHPStan\Testing\assertType('*ERROR*', $argc);
Please put this function in a use statement.

2022-09-20 15:56 UTC, merged

2022-09-20 15:56 UTC, ondrejmirtes commented
Thank you.