Add `Type::getLastIterableValueType()`
phpstan/phpstan-src pull request #1811
Opened 2022-10-10 15:23 UTC by herndlm

just playing around, kind of POC for moving more array-related methods to `Type` which I mentioned in https://github.com/phpstan/phpstan-src/pull/1801#issuecomment-1272401520. I'm not sure about this or if this should be the direction to move forward for other array return type extensions too.. 

What I like
- no special constant array handling and union type building anymore in `ArrayPopFunctionReturnTypeExtension`

What I dislike
- it's basically just for constant array and `array_pop` in particular

Most likely this is the best-case example and others will be more complicated to move over.

2022-10-10 15:51 UTC, ondrejmirtes requested changes
This totally makes sense to me. Maybe we could tackle first value at the same time? Thanks 😊

2022-10-10 15:51 UTC, ondrejmirtes commented on src/Type/Php/ArrayPopFunctionReturnTypeExtension.php
> +		return TypeCombinator::addNull($itemType);
This isn't strictly the same, if you didn't have a reason to change it, please revert it. It's problematic when a generic bound is nullable.

2022-10-10 15:53 UTC, herndlm commented on src/Type/Php/ArrayPopFunctionReturnTypeExtension.php
> +		return TypeCombinator::addNull($itemType);
oh, I wasn't even thinking about that and thought it's basically the same 🤯

2022-10-10 15:54 UTC, ondrejmirtes commented on src/Type/Php/ArrayPopFunctionReturnTypeExtension.php
> +		return TypeCombinator::addNull($itemType);
The difference is that TypeCombinator::containsNull() and NullType->isSuperTypeOf($type) are different things.

2022-10-10 16:15 UTC, ondrejmirtes commented
BTW a random thought - don't feel obligated to get the design right the first time, it doesn't have to be perfect 😊 We'll eventually deprecate some of the new methods anyway, as we come up with better alternatives 😊

2022-10-10 17:09 UTC, herndlm commented
> BTW a random thought - don't feel obligated to get the design right the first time, it doesn't have to be perfect 😊 We'll eventually deprecate some of the new methods anyway, as we come up with better alternatives 😊

Yes. But you know, it is _very_ important that they are sorted in the _right_ order 😅

2022-10-10 17:39 UTC, herndlm commented
I saw a couple more cases like this one, expect more PRs :) I'll look at the complex ones at the end

2022-10-11 13:07 UTC, herndlm commented
this is ready and I'm eager to add a couple more 😊

2022-10-11 13:37 UTC, ondrejmirtes approved these changes

2022-10-11 13:38 UTC, merged

2022-10-11 13:38 UTC, ondrejmirtes commented
Thank you :)