`sodium_crypto_generichash*` always produce a `non-empty-string`
phpstan/phpstan-src pull request #1981
Opened 2022-11-07 18:52 UTC by Slamdunk

`sodium_crypto_generichash` functions always return states or hashes as `non-empty-string` by design, see

1. https://doc.libsodium.org/hashing/generic_hashing
2. https://github.com/jedisct1/libsodium/blob/1.0.18/src/libsodium/crypto_generichash/blake2b/ref/generichash_blake2b.c

2022-11-07 20:48 UTC, ondrejmirtes requested changes

2022-11-07 20:48 UTC, ondrejmirtes commented on resources/functionMap.php
> +'sodium_crypto_generichash_final' => ['non-empty-string', 'state'=>'non-empty-string', 'length='=>'?int'],
Declaring parameter as `non-empty-string` gives me a little pause - what happens when the function receives an empty string? Unless it crashes, I wouldn't require it here.

2022-11-08 06:04 UTC, Slamdunk commented on resources/functionMap.php
> +'sodium_crypto_generichash_final' => ['non-empty-string', 'state'=>'non-empty-string', 'length='=>'?int'],
That's indeed what happens when you pass an empty string variable:

```
PHP Fatal error:  Uncaught SodiumException: incorrect state length
```

`libsodium` is very reliable

2022-11-08 06:44 UTC, merged

2022-11-08 06:44 UTC, ondrejmirtes commented
Thank you.