declare assert-if-true for filesystem functions
phpstan/phpstan-src pull request #1993
Opened 2022-11-13 19:10 UTC by staabm

2022-11-13 21:22 UTC, ondrejmirtes requested changes
Two problems here:

1) `chdir($dir) ? 'foo' : 'bar'`` - in the else branch `$dir` will be considered `''`
2) If you pass `non-empty-string` to `chdir(...)`, you'll get "always true" error.

Both can be solved with `=non-empty-string`. See: https://github.com/phpstan/phpstan/issues/8348 + https://github.com/phpstan/phpstan/issues/8351

2022-11-18 20:09 UTC, ondrejmirtes requested changes
To make sure that `=` actually fixes these problems, you should have tested the `else` condition types and also put a test about this in ImpossibleCheckTypeFunctionCallRule (before adding the `=` everywhere). Please verify this was originally a problem and that it's fixed after the change. I'm sure you can find the previous version in your reflog :) It's e117fce or 49564b7.

2022-11-20 12:05 UTC, staabm commented
good point.

```
2) PHPStan\Rules\Comparison\ImpossibleCheckTypeFunctionCallRuleTest::testBug6788
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'
+'13: Call to function chdir() with non-empty-string will always evaluate to true.
+    💡 Because the type is coming from a PHPDoc, you can turn off this check by setting <fg=cyan>treatPhpDocTypesAsCertain: false</> in your <fg=cyan>%configurationFile%</>.
+15: Call to function chdir() with non-falsy-string will always evaluate to true.
+    💡 Because the type is coming from a PHPDoc, you can turn off this check by setting <fg=cyan>treatPhpDocTypesAsCertain: false</> in your <fg=cyan>%configurationFile%</>.
 '
```

2024-06-12 12:09 UTC, staabm commented
the last commit is fixing cases like

```
<?php

namespace Bug4816;

use function PHPStan\Testing\assertType;

function (string $x): void {
	if (is_dir($x)) {
		assertType('true', is_dir($x));
	}
};
```

(so we don't regress https://github.com/phpstan/phpstan-src/commit/1eaef0463d2347bdbef3612da158853519867d82)

---

my understanding is, that because this PR adds stubs with `@phpstan-assert` the specifier did no longer invoke `handleDefaultTruthyOrFalseyContext` in

https://github.com/phpstan/phpstan-src/blob/7cd03f02a5c32ca4e51006dc21d6184f73835a14/src/Analyser/TypeSpecifier.php#L455-L472

and that the reason why my previous code sample did regress.

@rvanvelzen could you give me a hand? why do we not invoke `handleDefaultTruthyOrFalseyContext` when taking the path thru `specifyTypesFromAsserts`. is this expected or an oversight?

btw: I noticed we also don't invoke `handleDefaultTruthyOrFalseyContext` when we take the path thru `specifyTypesFromConditionalReturnType`.

2024-06-12 14:20 UTC, thg2k commented
I had **no** idea that the assertion would actually assert the opposite if the condition is not met. This is very counter-intuitive for me.. I think the behavior with "=" should be the default and there should rather be another modifier to request the double behavior.

2025-08-10 08:53 UTC, closed without merging