extract conditionalExpression resolving as a private method, and only…
phpstan/phpstan-src pull request #2030
Opened 2022-11-27 03:34 UTC by rajyan

… resolve types when needed

solves https://github.com/phpstan/phpstan/discussions/8397

I've improved the logic of `conditionalTypes` to only resolve conditional types when needed, instead of resolving all `conditionalTypes` every time `filterBySpecifiedTypes` is called.
I'm quite confident that this change can improve performance :)
Now, all I have to do is to pass all the tests!

2022-11-27 06:36 UTC, rajyan commented
https://github.com/phpstan/phpstan-src/pull/2030/commits/653c00b606fc275507702517539c812a75b1807f
should fix the failing test, but would make a huge performance regression again.
I need a better way to resolve all conditionalTypes before merging and `createConditionalExpressions`

2022-11-27 06:50 UTC, ondrejmirtes commented
This looks promising 😊

Please run `time make phpstan` on 1.9.2, on 1.9.x and on your branch, so we can compare the numbers 😊 Thank you.

2022-11-27 07:10 UTC, rajyan commented
I'm running `hyperfine -i 'make phpstan'` on every commit to check the performance
The current result is
```
# 1.9.2
  Time (mean ± σ):     18.332 s ±  0.975 s    [User: 114.153 s, System: 1.781 s]
  Range (min … max):   17.655 s … 20.206 s    10 runs

# 1.9.x
  Time (mean ± σ):     25.188 s ±  0.866 s    [User: 137.685 s, System: 1.855 s]
  Range (min … max):   24.466 s … 27.309 s    10 runs

# @42bddf02 (before the latest commit)
  Time (mean ± σ):     19.993 s ±  1.222 s    [User: 121.689 s, System: 1.802 s]
  Range (min … max):   19.240 s … 22.366 s    10 runs
```

2022-11-27 08:48 UTC, ondrejmirtes commented
Looks great 😊

2022-11-28 00:12 UTC, rajyan commented
This is something like resolving the conditional types as late as it can.
The problem I'm having now is conditional types that could have been resolved is deleted before being resolved when merging scopes.
As we can see in
https://github.com/phpstan/phpstan-src/blob/42bddf0262d38dccb34aa9670335956ed6047a15/src/Analyser/MutatingScope.php#L3904
when merging, we can only "intersect" conditional types.

simple example
```php
if ($a) {
  // conditional type $c='foo' => $b = 'foo'
} else {
  // conditional type $c='bar' => $b = 'bar'
}

// whats the conditional type here? Currently they are deleted while intersecting
// maybe we can merge them like $a=truthty&&$c=true => $b='foo', $a=falsy&&$c=true => $b='bar'
```

2022-11-28 00:57 UTC, rajyan commented
Three failing tests are related to `createConditionalExpressions`
One is related to this commented out lines
https://github.com/phpstan/phpstan-src/pull/2030/files#diff-dc817f2bab8672057a95375a542e68599164f6ab2380e4cccd1b50583e295d85R3580-R3589

2022-11-28 09:49 UTC, ondrejmirtes commented
Unfortunately you're on your own, I hope you figure it out, I'm following it closely :) It'd take me a few days to load everything into my brain and it's already in yours so you'll be faster in finishing it I'm sure :)

2022-11-29 00:34 UTC, rajyan commented
I debugged further
https://gist.github.com/rajyan/e8b66dc43c4df4fef0d6fcc139ca0597

bug-987 shows whats happening
https://github.com/phpstan/phpstan-src/blob/579b075806f32076dfaf55a4f2c913f55ed14a5c/tests/PHPStan/Analyser/data/bug-987.php#L38-L51

```php
	/**
	 * @return string[]
	 */
	function hello(self $class, bool $boolOption): array
	{
		$myArray = $class->arrOrNull();
		if ($boolOption && $myArray === null) {
			throw new \Exception('');
		}
		// !$boolOption or $boolOption=true => $myArray=array<string>
		if (!$boolOption) {
			$myArray = $class->otherGetArray();
			// $myArray=array<string> in inner scope
		}
		// filterByFalsyValue(!$boolOption) => $boolOption=true, so outer scope can resolve $boolOption=true => $myArray=array<string>
                // Although, in [fix-conditional-performance](https://github.com/rajyan/phpstan-src/tree/fix-conditional-performance) this conditional is not resolved $myArray=array<string>|null
		// inner scope and outer scope is merged

		assertType('array<string>', $myArray);

		return $myArray;
	}
```

2022-11-29 00:57 UTC, rajyan commented
I think adding this kind of conditional type
https://github.com/phpstan/phpstan/issues/8360#issuecomment-1314848512
can solve this problem.
Maybe something can be improved in
https://github.com/phpstan/phpstan-src/blob/f8f09cdb60a0a6214199f5a765a7782cb110e52e/src/Analyser/NodeScopeResolver.php#L3420-L3427
but not sure yet.

2022-11-30 01:23 UTC, rajyan commented on src/Analyser/MutatingScope.php
> +		}
I'm not satisfied enough with this implementation, but this works at least.
I think after conditional types merging logic has improved, we can delete matching ConditionExpressionTypeHolders

2022-11-30 01:37 UTC, rajyan commented on src/Analyser/MutatingScope.php
> +		//      }
Now the only thing to solve is this

2022-11-30 14:41 UTC, janedbal commented on src/Analyser/MutatingScope.php
> +		//      }
Waiting impatiently for the fix :)

2022-12-01 01:04 UTC, rajyan commented
Hmm
this rector integration test error
```
 ------ ----------------------------------------------------------------------- 
  Line   rules/Naming/Naming/ExpectedNameResolver.php                           
 ------ ----------------------------------------------------------------------- 
  187    Parameter 1 should use "PHPStan\Type\ArrayType" type as the only type  
         passed to this method                                                  
 ------ ----------------------------------------------------------------------- 
```
doesn't look correct.

2022-12-02 00:17 UTC, rajyan commented
I'm very satisfied with this implementation. Gonna update the pull request description for explanation!

2022-12-02 00:40 UTC, rajyan commented
```
╭─ ~/Contribution/phpstan-src  fix-conditional-performance *5 ·································································································· INT ✘  1m 5s  09:27:59 
╰─ hyperfine -i 'make phpstan'
Benchmark 1: make phpstan
  Time (mean ± σ):     20.455 s ±  0.942 s    [User: 118.691 s, System: 1.995 s]
  Range (min … max):   19.193 s … 21.805 s    10 runs
 
╭─ ~/Contribution/phpstan-src  fix-conditional-performance *5 ····································································································· ✔  3m 25s  09:31:47 
╰─ git switch --detach 1.9.2
HEAD is now at 582a9cb8b Fix unset on nested array
╭─ ~/Contribution/phpstan-src  #1.9.2 *5 ··································································································································· ✔  09:32:07 
╰─ hyperfine -i 'make phpstan'
Benchmark 1: make phpstan
  Time (mean ± σ):     18.278 s ±  0.598 s    [User: 114.610 s, System: 1.880 s]
  Range (min … max):   17.741 s … 19.564 s    10 runs

 
╭─ ~/Contribution/phpstan-src  #1.9.2 *5 ··························································································································· ✔  3m 3s  09:35:11 
╰─ git switch --detach 1.9.x  
Previous HEAD position was 582a9cb8b Fix unset on nested array
HEAD is now at 70a87cceb ImagickPixel::getColor() normalized param accepts int instead of bool
Your branch is up to date with 'origin/1.9.x'.
╭─ ~/Contribution/phpstan-src  @70a87cce *5 ································································································································ ✔  09:35:19 
╰─ hyperfine -i 'make phpstan'
Benchmark 1: make phpstan
  Time (mean ± σ):     25.497 s ±  0.776 s    [User: 138.297 s, System: 1.844 s]
  Range (min … max):   24.355 s … 26.668 s    10 runs

```

2022-12-02 07:22 UTC, ondrejmirtes requested changes
Awesome, looks great 😊

1) Please add a regression test for #5805, check the issue bot.
2) Did you check all the failures? Are they improvements?

thank you!

2022-12-02 07:39 UTC, rajyan commented
> Please add a regression test for #5805, check the issue bot.

Oh, thanks! I wasn't aware with the issue bot result change.
I'll add it as soon as I get back home:)

> Did you check all the failures? Are they improvements?

Sorry I forgot to comment about it.
The only changed test result is
https://github.com/phpstan/phpstan-src/actions/runs/3597748538/jobs/6059882549
and I believe this is a improvement

https://github.com/PrestaShop/PrestaShop/blob/38d8ad3ef7a2faa6b6db73b0a19768d2be3dc85c/controllers/admin/AdminImportController.php#L3094-L3101
here `$customer_exist` is only set to true once, so `isset($current_id_customer), isset($current_id_shop_group), isset($current_id_shop)` is always true if `$customer_exist = true`

https://github.com/PrestaShop/PrestaShop/blob/38d8ad3ef7a2faa6b6db73b0a19768d2be3dc85c/controllers/admin/AdminProductsController.php#L689
the `isset` is redundant because conditional type with expression  `Configuration::get('PS_ADVANCED_STOCK_MANAGEMENT')` is now working and we know that it's always assigned in line 687.

2022-12-02 07:53 UTC, herndlm commented
Very nice indeed 🎉

2022-12-02 07:58 UTC, rajyan commented
Confirm that added regression test fails with 1.9.x

2022-12-02 08:00 UTC, merged

2022-12-02 08:01 UTC, ondrejmirtes commented
Thank you!

I'll try to run it with Blackfire to compare 1.9.2 and the new 1.9.x to see what can be done, after the weekend.

2022-12-02 08:52 UTC, staabm commented
great job @rajyan 👍