Synchronized functionMap with PDO, PDOException and PDOStatement
phpstan/phpstan-src pull request #2036
Opened 2022-11-30 14:04 UTC by kang8

Sync from PHP official manual: https://www.php.net/manual/en/book.pdo.php

2022-11-30 15:06 UTC, staabm commented
if this change is triggered by a particular bug (or code sample) it would be great to have a unit test in addition to the changes

2022-11-30 15:09 UTC, kang8 commented
I will add unit tests tomorrow.

2022-12-01 14:09 UTC, ondrejmirtes requested changes
Renaming these parameters is entirely unnecessary and counterproductive. Please submit only the type changes instead.

2022-12-03 11:25 UTC, kang8 commented
cc @staabm 

I do not know how to test `resource/functionMap.php`. Furthermore, I tried to go to the previous commits by `resources/functionMap.php` (git log -p resource/functoinMap.php). I find `SignatureMapParseTest::testParseAll()` to test the whole file by `resource/functionMap.php`.

https://github.com/phpstan/phpstan-src/blob/531b9e1c7bcc16c11295c20b77cde09061d76097/tests/PHPStan/Reflection/SignatureMap/SignatureMapParserTest.php#L496

I think the test is enough for now. Testing against a particular function is repetitive and not worth writing tests for.

2022-12-03 11:37 UTC, staabm commented
is this change triggered by a concrete code example which does not work for you?

if so, take this code, put it into a file under `tests/PHPStan/Analyser/data/` add `assertType` calls and yield it from within `NodeScopeResolverTest->dataFileAsserts()` (append it to the bottom of all existing yields).

most of the time a test is mandatory to prevent regressions.

2022-12-03 14:50 UTC, staabm commented on tests/PHPStan/Analyser/data/pdo-quote.php
> +		assertType('(string|false)', $quote_string);
per function map this should be

```suggestion
		assertType('string|false', $quote_string);
```

2022-12-04 08:31 UTC, ondrejmirtes requested changes

2022-12-04 08:31 UTC, ondrejmirtes commented on resources/functionMap.php
> +'PDO::query' => ['PDOStatement|false', 'sql'=>'string', 'fetchMode='=>'int<0,5>'],
You could reference the constants instead: [PDO::FETCH_*](https://www.php.net/manual/en/pdo.constants.php)

2022-12-04 08:31 UTC, ondrejmirtes commented on resources/functionMap.php
> +'PDO::query\'2' => ['PDOStatement|false', 'sql'=>'string', 'fetch_class='=>'int<0,5>', 'classname='=>'string', 'ctorargs='=>'array'],
I don't think these parameters need to become optional with `=`.

2022-12-04 08:31 UTC, ondrejmirtes commented on resources/functionMap.php
> +'PDOStatement::fetchAll' => ['array', 'mode='=>'int'],
These can definitely still return `false` on PHP 7.x.

2022-12-16 09:59 UTC, ondrejmirtes commented
Tests are failing.

2022-12-19 11:48 UTC, kang8 commented
@ondrejmirtes fixed failed tests, can review now.

2022-12-19 15:00 UTC, ondrejmirtes commented
There are failures in tested projects:

* https://github.com/phpstan/phpstan-src/actions/runs/3730184925/jobs/6326974195
* https://github.com/phpstan/phpstan-src/actions/runs/3730184925/jobs/6326974877

It's what happens when we narrow parameter types like that. I'm not sure if I want to drop this on users :)

2023-02-06 01:22 UTC, kang8 commented
`dbal` PDO static analysis has been solved by doctrine/dbal#5883. Wait for `3.5.4` to tag, I will reopen a PR and rebase to 1.10.x.

And also change https://github.com/phpstan/phpstan/blob/f9f7d4a0714c8356ebe3a14e328a0a6dc778d454/.github/workflows/integration-tests.yml#L219 to `3.5.4`.

2023-02-07 20:01 UTC, derrabus commented
> Wait for `3.5.4` to tag

https://github.com/doctrine/dbal/releases/tag/3.5.4

2023-02-10 01:48 UTC, kang8 commented
All PDO type static analysis in dbal have been solved:
* https://github.com/phpstan/phpstan-src/actions/runs/4139955654/jobs/7158142441

2023-02-15 02:15 UTC, kang8 commented
There are still some test failures. I'm not sure if they are related to my modification. @ondrejmirtes could you give me some suggestions?

2023-07-15 06:13 UTC, kang8 commented
Close it, cause is inactive.

2023-07-15 06:13 UTC, closed without merging

2023-07-15 06:17 UTC, staabm commented
Fywiw, we have a bleedingEdge functionMap for breaking signature changes like this. 

Maybe it could land there?

2023-07-15 06:22 UTC, kang8 commented
> we have a bleedingEdge functionMap for breaking signature changes like this.

Cool! I will go and do some research.

Next, I will proceed with this PR and target it towards the latest branch

2023-07-18 10:54 UTC, kang8 commented
> bleedingEdge functionMap for breaking signature changes like this

I don't think land to bleedingEdge functionMap is a good choice. 

Is there any problem with my current approach?

2023-07-18 11:33 UTC, staabm commented
See https://github.com/phpstan/phpstan-src/pull/2036#issuecomment-1357795623