Support contravariant template types
phpstan/phpstan-src pull request #2051
Opened 2022-12-05 18:36 UTC by jiripudil

Closes phpstan/phpstan#3960.

Basically, I'm picking up where #1492 left off, with a couple more tests.

Once this lands, I'd like to follow up with a fix to the bug mentioned in the original PR (https://github.com/phpstan/phpstan-src/pull/1492#discussion_r912294565). The logs are no longer available for the relevant builds, but I understand it caused some turmoil, and should therefore be discussed separately.

2022-12-05 18:47 UTC, ondrejmirtes requested changes
I'd like some "accepts" tests, meaning "does this parameter accept this argument"? For example in CallMethodsRuleTest, to see that the objects behave correctly :)

2022-12-05 20:26 UTC, jiripudil commented
I'm assuming you have something like this in mind? Otherwise, apart from a detail irrelevant to this case, `GenericObjectType::accepts()` shares the implementation with `isSuperTypeOf()` which is already covered by tests. But can't hurt to have an integration test on top of that :)

2022-12-05 20:31 UTC, ondrejmirtes commented
Yes, thank you :)

2022-12-05 20:31 UTC, merged

2023-06-26 15:29 UTC, oprypkhantc commented
Thank you for picking up on it @jiripudil :)