NeverType: accept nothing
phpstan/phpstan-src pull request #2110
Opened 2022-12-14 09:39 UTC by jiripudil

I was surprised to find out that `NeverType` accepts everything. Shouldn't it be the opposite? It's the bottom type, it's empty. No value can be of this type. Why accept _every_ value then?

Consider this PR me poking around and waiting to see what builds break.

2022-12-14 09:53 UTC, ondrejmirtes commented
An idea - only explicit never should have this behaviour. If you have implicit never, it means that the function signature is wrong, and you already have an error at the declaration - no need for a new error when calling it :)

2022-12-14 11:01 UTC, staabm commented
interessting :)

you should have a look at the impact this change has on open issues: https://github.com/phpstan/phpstan-src/actions/runs/3693563281

2022-12-14 11:47 UTC, jiripudil commented
> An idea - only explicit never should have this behaviour. If you have implicit never, it means that the function signature is wrong, and you already have an error at the declaration - no need for a new error when calling it :)

Oh, thanks a lot for this comment! This probably explains why it has been implemented to accept everything. I'll update this so that only the behaviour of explicit never is changed 👍

2022-12-15 12:52 UTC, ondrejmirtes requested changes
Thank you, it makes total sense and issue bot agrees :)

Please:

1) Add a regression test for the one implemented feature request that asks for this :)
2) Please add a test that shows that explicit `never` can be passed into explicit `never` :)

2022-12-15 16:08 UTC, merged

2022-12-15 16:08 UTC, ondrejmirtes commented
Thank you!

2022-12-15 16:34 UTC, ondrejmirtes commented
I'm really gonna go crazy here :D Because of this change, this now reports problem like this:

```

 ------ ----------------------------------------------------------------------- 
  Line   test.php                                                
 ------ ----------------------------------------------------------------------- 
  73     Parameter #1 $element of method                                        
         Doctrine\Common\Collections\ArrayCollection<*NEVER*,*NEVER*>::add()    
         expects *NEVER*,                                                       
         object given.                                                    
 ------ ----------------------------------------------------------------------- 
```

So if you create a new ArrayCollection and immediately try to add something to it, it's gonna report an error.

Maybe we'll have to postpone this until generics are smarter 🤔

2022-12-16 08:25 UTC, herndlm commented
That's https://github.com/phpstan/phpstan/discussions/8511 / https://github.com/phpstan/phpstan/discussions/6731 again, right? Did you not see the failing test Ondřej? :P