Do not report errors on required params following optional ones
phpstan/phpstan-src pull request #2218
Opened 2023-02-03 16:27 UTC by Wirone

Such code is working as expected and PHPStan should not enforce changes there.

[Slack discussion](https://symfony-devs.slack.com/archives/C8SFXTD2M/p1675439658867819), [playground example](https://phpstan.org/r/d397543b-22b7-4da0-8780-ca45f30620a9).

2023-02-03 16:36 UTC, ondrejmirtes requested changes
Do not remove the error, just remove the nonIgnorable part.

2023-02-03 16:48 UTC, Wirone commented
Ah snap! I'll do it in the evening. Went to basketball game 😉

2023-02-03 19:15 UTC, Wirone commented
@ondrejmirtes Should test be added for scenario with `@phpstan-ignore-*`? And I don't know why actions complain about changed title - I changed it so it better describes the change 🤷

2023-02-06 10:42 UTC, merged

2023-02-06 10:42 UTC, ondrejmirtes commented
Thank you.