Check filter_input* type param type
phpstan/phpstan-src pull request #2271
Opened 2023-03-04 20:42 UTC by herndlm

Specifying invalid ints there fails with a fatal error since PHP 8, see https://3v4l.org/2QvBP and https://3v4l.org/EP3T8
It would also be wrong on pre PHP 8 but there's no fatal error there at least.

This is the easiest I could come up with to check this, but it feels a bit weird. Any better ideas?

2023-03-08 13:33 UTC, ondrejmirtes commented
Although it makes the code safer, it can be quite annoying to require users to write a more specific PHPDoc type in their `@param`.

We need to figure out a way how to do these changes only in bleedingEdge. Then we'd also be albe to merge this https://github.com/phpstan/phpstan-src/pull/2163 and this https://github.com/phpstan/phpstan-src/pull/2217.

2023-03-08 14:24 UTC, staabm commented
> We need to figure out a way how to do these changes only in bleedingEdge

what do you think about enabling these errors only when bleedingEdge and strict-rules are enabled?

2023-03-08 14:36 UTC, herndlm commented
makes sense, thx for the inputs! I thought here it might be okay, because nobody ever should call these functions differently. I think it's a bit different compared to the linked PRs, but I get the general problem and point :)

2023-04-05 08:45 UTC, ondrejmirtes requested changes

2023-04-05 08:45 UTC, ondrejmirtes commented on resources/functionMap_php80delta.php
> +		'filter_input' => ['mixed', 'type'=>'INPUT_GET|INPUT_POST|INPUT_COOKIE|INPUT_SERVER|INPUT_ENV', 'variable_name'=>'string', 'filter='=>'int', 'options='=>'array|int'],
Please do stricter parameter types in `functionMap_bleedingEdge.php`. If this is only PHP 8+ specific, please create `functionMap_php80delta_bleedingEdge.php`. Thank you!

2023-04-13 18:38 UTC, ondrejmirtes approved these changes

2023-04-13 18:38 UTC, merged

2023-04-13 18:39 UTC, ondrejmirtes commented
Thank you!