Fix `get_class()` on HasMethodType
phpstan/phpstan-src pull request #2350
Opened 2023-04-19 13:24 UTC by staabm

closes https://github.com/phpstan/phpstan/issues/4890

2023-04-19 13:35 UTC, ondrejmirtes requested changes

2023-04-19 13:35 UTC, ondrejmirtes commented on src/Type/Php/GetClassDynamicReturnTypeExtension.php
> +					return new ClassStringType();
I think it'd make more sense to get rid of this whole monstrosity (because it'd still fail for HasPropertyType for example - feel free to add a test for it) and also other types like ObjectShapeType.

Instead the whole `TypeTraverser::map` should be replacable with some methods called on `Type`.

* `Type::isObject()->no()` - always returns false
* `Type::isObject()->yes()` - never returns false
* `Type::isObject()->maybe()` - might return false

As for the actual type, you could do something like this:

```php
new GenericClassStringType(TypeCombinator::intersect($argType, new ObjectWithoutClassType()));
```

It will change the result in some cases but it will still be correct.

2023-04-19 16:31 UTC, staabm commented on src/Type/Php/GetClassDynamicReturnTypeExtension.php
> +			}
I am sure you won't like it, but I think it seems to be necessary.

without this case we get things like
`class-string<object{foo: Bug4890\HelloWorld, bar: int, baz?: string}>`

when intersecting `ObjectShapeType` and `ObjectWithoutClassType`.

2023-04-19 16:32 UTC, staabm commented on src/Type/Php/GetClassDynamicReturnTypeExtension.php
> +					return new ClassStringType();
I think your idea works pretty good. one exception is

```
 PHPStan\Analyser\NodeScopeResolverTest::testFileAsserts with data set "C:\dvl\Workspace\phpstan-src-staabm\tests\PHPStan\Analyser/data/bug-7167.php:11" ('type', 'C:\dvl\Workspace\phpstan-src-...67.php', PHPStan\Type\Constant\ConstantStringType Object (...), PHPStan\Type\Generic\GenericClassStringType Object (...), 11)
Expected type class-string<Bug7167\Foo>, got type class-string<Bug7167\Foo::Value> in C:\dvl\Workspace\phpstan-src-staabm\tests\PHPStan\Analyser/data/bug-7167.php on line 11.
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'class-string<Bug7167\Foo>'
+'class-string<Bug7167\Foo::Value>'
```

which I am not yet sure how to handle

2023-04-26 05:33 UTC, staabm commented on tests/PHPStan/Analyser/data/bug-4890.php
> +class HelloWorld
see https://phpstan.org/r/b6b95d5a-a3fb-4c29-be47-4e7832f00ddc regarding how this test fails before this PR

2023-04-26 05:33 UTC, staabm commented
I think I figured it out

2024-01-06 13:28 UTC, ondrejmirtes requested changes

2024-01-06 13:28 UTC, ondrejmirtes commented on src/Type/Php/GetClassDynamicReturnTypeExtension.php
> +				if ($isObject->yes() || $isObject->maybe()) {
For which type here it's going to be a `maybe`?

2024-01-06 13:28 UTC, ondrejmirtes commented on src/Type/Php/GetClassDynamicReturnTypeExtension.php
> +						$objectType = $objectType->getStaticObjectType();
Why are you checking this after an intersection?

2026-02-10 16:42 UTC, closed without merging