Fix loose comparison against enum
phpstan/phpstan-src pull request #2410
Opened 2023-05-19 15:28 UTC by schlndh

Here is an attempt to make PHPStan understand loose comparisons with enums better.

My motivation for this is that I'm converting a bunch of "enum classes" (based on `consistence/consistence`) into native enums. And I encountered a case like this, which was not reported by PHPStan, even though it doesn't work after the conversion: `in_array($enum, ['A', 'B'])`. Previously it worked because the enum class had `__toString()` implemented.

Here are the results for a bunch of loose comparisons: https://3v4l.org/Huc7t

Note that the PHP documentation says the following:

> While identity comparison (=== and !==) can be applied to arbitrary values, the other comparison operators should only be applied to comparable values. The result of comparing incomparable values is undefined, and should not be relied upon. 

So it is possible, that what I'm trying to achieve either doesn't make sense, or may be too version dependent. However, as far as I can tell, it does not clearly specify which types are comparable.

2023-05-23 13:07 UTC, ondrejmirtes requested changes
`InArrayFunctionTypeSpecifyingExtension` is a type-specifying extension, meaning the changes inside should also have their own tests - what the type of the argument is after true/false `in_array()` check.

2023-05-24 17:05 UTC, schlndh commented on src/Type/Php/InArrayFunctionTypeSpecifyingExtension.php
> +					|| count(TypeUtils::getEnumCaseObjects($needleType)) === 1
This fixes https://phpstan.org/r/9c8038c6-783f-4eab-beab-e9ee525cff8c

2023-05-24 17:07 UTC, schlndh commented on src/Type/Php/InArrayFunctionTypeSpecifyingExtension.php
>  			|| (
I haven't been able to figure out whether `$context->true()` can actually do anything. I tried commenting it out and it didn't break any tests. As far as I was able to tell, the specified types are mostly intersected with the original type, in which case widening the specified type doesn't do anything.

2023-05-25 11:10 UTC, merged

2023-05-25 11:10 UTC, ondrejmirtes commented
Thank you!