Static methods are no longer callable
phpstan/phpstan-src pull request #2420
Opened 2023-05-28 08:42 UTC by staabm

refs https://github.com/phpstan/phpstan/issues/5782

as suggested in https://github.com/phpstan/phpstan/issues/5782#issuecomment-1559321986

2023-05-28 08:43 UTC, staabm commented on src/Type/Constant/ConstantArrayType.php
> +			if ($method->isStatic()) {
actually this should depend on php-version.
within the type-classes we don't have access to `PhpVersion` though

2023-06-22 09:16 UTC, staabm commented
I think it works as expected now - at least what php8 is concerned.

we don't know the php version in the type-system, so I can't differentiate between php7/8. is it acceptable as is?

2023-06-22 09:21 UTC, ondrejmirtes requested changes
There are examples how to approach DI-registered values or services in places where DI isn't available:

* https://github.com/phpstan/phpstan-src/blob/1.11.x/src/DependencyInjection/BleedingEdgeToggle.php
* https://github.com/phpstan/phpstan-src/blob/1.11.x/src/Reflection/ReflectionProviderStaticAccessor.php

For current methods we could add `PhpVersionAccessor` so that we can ask about the PHP version.

For future methods we should require `PhpVersion` as a parameter.

2023-06-22 11:31 UTC, staabm commented on tests/PHPStan/Rules/Methods/data/call-methods.php
> +		// $this->test('Test\CheckIsCallable::test'); differs between php7/8; tested separately
moved this line into a separate new test, so I don't need to duplicate the whole `call-methods.php` assertions and can keep the diff small

2023-06-22 11:37 UTC, staabm commented
the errors in the Carbon build job seem legit. [related source](https://github.com/briannesbitt/Carbon/blob/94e1178370787843424b276b334a03da6f0abb3d/src/Carbon/CarbonPeriod.php#L181-L200)

2023-06-22 11:47 UTC, merged

2023-06-22 11:48 UTC, ondrejmirtes commented
Thank you.