Implement reportUncheckedExceptionDeadCatch
phpstan/phpstan-src pull request #2648
Opened 2023-09-25 14:10 UTC by VincentLanglet

2023-09-28 13:28 UTC, ondrejmirtes requested changes

2023-09-28 13:28 UTC, ondrejmirtes commented on src/Rules/Exceptions/CatchWithUnthrownExceptionRule.php
> +		$isCheckedException = TrinaryLogic::createFromBoolean($this->reportUncheckedExceptionDeadCatch)->lazyOr(
This code isn't very readable to me. We want to early-return only if `$this->reportUncheckedExceptionDeadCatch` is false. So please do all this logic inside `if (!$this->reportUncheckedExceptionDeadCatch) { ... } `.

Thank you.

2023-09-28 13:43 UTC, ondrejmirtes commented
Much better, thank you. Please also send an update to the documentation and the blogpost.

2023-09-28 13:43 UTC, merged

2023-09-29 14:06 UTC, ondrejmirtes commented
Still waiting for that docs update :)

2023-09-29 14:10 UTC, VincentLanglet commented
> Still waiting for that docs update :)

Sorry for the delay, it's definetly in my TODO

2023-09-29 14:51 UTC, VincentLanglet commented
I did https://github.com/phpstan/phpstan/pull/9944 @ondrejmirtes