Don't collapse Traversable with php-src native traversable objects
phpstan/phpstan-src pull request #2676
Opened 2023-10-12 14:30 UTC by staabm

closes https://github.com/phpstan/phpstan/issues/10008

2023-10-12 14:50 UTC, staabm commented on tests/PHPStan/Analyser/data/dba-traversables.php
> +class HelloWorld
before this PR: https://phpstan.org/r/6c9c4317-0a4e-4c63-a06b-79865b9aaea3

2023-10-12 15:03 UTC, ondrejmirtes requested changes

2023-10-12 15:03 UTC, ondrejmirtes commented on src/Type/Generic/GenericObjectType.php
> +		if ($this->getClassName() === Traversable::class) {
You can't special-case this about `Traversable`, this needs to work generally.

2023-10-23 21:18 UTC, ondrejmirtes commented
I tried a fix and it's hard: https://github.com/phpstan/phpstan/issues/10008#issuecomment-1761062790

2023-10-23 21:18 UTC, closed without merging