fix named arguments for few multi-variant methods
phpstan/phpstan-src pull request #2748
Opened 2023-11-19 10:08 UTC by schlndh

There are a few cases where PHPStorm stubs have the wrong parameter names. So I'd remove the parameter rename for named params. Since named params are only available from PHP 8, we should have the correct names from php-8-stubs.

2023-11-19 13:21 UTC, ondrejmirtes requested changes
Please tell me where the "named argument variants" are being read from phpstorm-stubs. I'd say that PHP functions in php-8-stubs should always be read from there.

2023-11-19 13:21 UTC, ondrejmirtes commented on src/Reflection/Php/PhpClassReflectionExtension.php
> +								$phpDocParameterNameMapping = [];
What is the significance of this change?

2023-11-19 13:59 UTC, schlndh commented
> Please tell me where the "named argument variants" are being read from phpstorm-stubs. I'd say that PHP functions in php-8-stubs should always be read from there.

It's not the "named argument variants" that are being read from phpstorm-stubs. But the arguments are renamed based on the phpstorm-stubs. It's exactly the change that you highlighted (`$phpDocParameterNameMapping = []`) that turns this off for named arguments.

2023-11-19 19:34 UTC, ondrejmirtes commented
So let's say that in phpstorm-stubs there's:

```php
/**
 * @param int $a
 * @param string $b
 */
public function foo($a, $b): void
```

And in reality the named arguments are named:

```php
public function foo($c, $d): void
```

I'd still expect them to be typed with int and string based on the PHPDoc from phpstorm-stubs.

Is that what this PR changes? Or something else?

2023-11-19 19:54 UTC, schlndh commented
You're right - the `$phpDocParameterNameMapping` is still needed inside `createNativeMethodVariant` to match the phpdoc types etc. Currently it makes no difference since the named variants are only used for multi-variant methods. But if they were to expand, it might have caused some bugs. I changed it accordingly.

2023-11-20 09:03 UTC, merged

2023-11-20 09:03 UTC, ondrejmirtes commented
Thank you!