Implement DeclarePositionRule
phpstan/phpstan-src pull request #2759
Opened 2023-11-21 11:17 UTC by staabm

closes https://github.com/phpstan/phpstan/issues/6195

2023-11-21 11:25 UTC, mad-briller commented
does this ignore `declare` used for [purposes other than](https://phpstan.org/r/afae2682-8ec3-4f74-b555-92daf62bad46) `strict_types`?

2023-11-21 11:35 UTC, staabm commented
good catch - fixed thanks

2023-11-21 11:49 UTC, ondrejmirtes commented
Please name this accordingly "DeclareStrictTypesRule" and also check nonsense in the directive, like `'foo'` instead of 0/1.

2023-11-21 12:11 UTC, ondrejmirtes requested changes

2023-11-21 12:11 UTC, ondrejmirtes commented on src/Rules/Keywords/DeclareStrictTypesRule.php
> +			$validValues = new UnionType([new ConstantIntegerType(0), new ConstantIntegerType(1)]);
Please don't use the type system for this, just the AST. I'm pretty sure some stuff is not allowed that would slip through this.

2023-11-22 08:21 UTC, ondrejmirtes requested changes

2023-11-22 08:21 UTC, ondrejmirtes commented on src/Rules/Keywords/DeclareStrictTypesRule.php
> +						'Declare strict_types must have 0 or 1 as its value.',
This message could be improved with `'Declare strict_types must have 0 or 1 as its value, %s given.'`

2023-11-22 09:08 UTC, merged

2023-11-22 09:08 UTC, ondrejmirtes commented
Thank you!

2023-11-25 10:32 UTC, ondrejmirtes commented
Hey @staabm this rule now causes a false positive: https://phpstan.org/r/adec71c6-2f0f-41b0-afc2-5df3f9110bce

Please look into it as it's currently blocking a release. Thank you.

2023-11-25 11:40 UTC, staabm commented
I am on vacation and can have a look on sunday