Narrow enum_exists() arg to UnitEnum
phpstan/phpstan-src pull request #2764
Opened 2023-11-22 08:37 UTC by staabm

closes https://github.com/phpstan/phpstan/issues/10169

2023-11-22 09:10 UTC, ondrejmirtes requested changes

2023-11-22 09:10 UTC, ondrejmirtes commented on src/Type/Php/ClassExistsFunctionTypeSpecifyingExtension.php
> +			return $this->typeSpecifier->create(
Please less code duplication here. The only thing different is the type argument.

2023-11-25 10:43 UTC, merged

2023-11-25 10:43 UTC, ondrejmirtes commented
Thank you.

2023-11-27 15:29 UTC, ZejdCicak commented
This makes `enum_exists` always treat an enum as UnitEnum, and never as BackedEnum, do you think there is a way to deal with this in library?

2023-11-27 15:30 UTC, ondrejmirtes commented
@ZejdCicak Please open a new issue with a reproducing snippet of your problem.