Update function map for ext-mongodb 1.17
phpstan/phpstan-src pull request #2768
Opened 2023-11-23 09:49 UTC by alcaeus

2023-11-25 10:23 UTC, ondrejmirtes requested changes

2023-11-25 10:23 UTC, ondrejmirtes commented on resources/functionMap.php
> +'MongoDB\BSON\fromJSON' => ['string', 'json' => 'string'],
Because of the `=>` and ` => ` change this is very hard to review. Please do not change this formatting as the rest of the file also use `=>`.

2023-11-26 18:35 UTC, alcaeus commented
You can view changes without whitespaces: https://github.com/phpstan/phpstan-src/pull/2768/files?diff=unified&w=1

There are a few lines at the bottom that also have that space, and the tooling we use outputs the code with whitespaces as they are required by other tools where we re-use this code (e.g. Psalm). If you insist I can remove them, but it's an extra effort I'd like to avoid as we're already having to update these stubs in three places.

I'm also happy to create a separate pull request that adds whitespaces to the rest of the file to make it compliant with widely accepted coding standards.

2023-11-26 18:52 UTC, thg2k commented
Despite me also being fond of coding style, making such a big change on a stable branch just for the sake of coding style is unwise. It would cause all kinds of conflicts on other open PRs, WIPs, and altered forks

2023-11-27 12:30 UTC, ondrejmirtes commented
I just unified the array format in functionMap: https://github.com/phpstan/phpstan-src/commit/97d9ddfe9c7c2875330d0dc9ddca69a7895abbf5

Please fix the formatting of your PR.

2023-11-27 12:45 UTC, merged

2023-11-27 12:45 UTC, ondrejmirtes commented
Thank you.

2023-11-27 12:46 UTC, alcaeus commented
> I just unified the array format in functionMap: [97d9ddf](https://github.com/phpstan/phpstan-src/commit/97d9ddfe9c7c2875330d0dc9ddca69a7895abbf5)
> 
> Please fix the formatting of your PR.

For the record, there are spaces on first array level, e.g.:
```php
'MongoDB\Driver\WriteConcern::unserialize' => ['void', 'data'=>'string'],
```

Not sure why the parameter list is special in that regard, especially considering that the rest of the source code uses different formatting, but it's not my call 🤷‍♂️