add filename and line number to phpunit output
phpstan/phpstan-src pull request #2775
Opened 2023-11-24 17:04 UTC by oadam

2023-11-24 17:12 UTC, ondrejmirtes commented
Please link some proof this is part of the JUnit standard.

2023-11-24 17:38 UTC, oadam commented
I amended the commit to try and justify the inclusion. Seems like there is no agreed upon junit standard :cry: !

no xsd here :
https://github.com/sebastianbergmann/phpunit/blob/main/src/Logging/JUnit/JunitXmlLogger.php#L298

discussion of the absence of proper junit xsd here :
https://github.com/sebastianbergmann/phpunit/issues/2964

Doing the same as phpunit should be safe ?

2023-11-24 17:39 UTC, oadam commented
Some of the attributes I have added are added here in PHPUnit : https://github.com/sebastianbergmann/phpunit/blob/main/src/Logging/JUnit/JunitXmlLogger.php#L428

2023-11-25 10:48 UTC, ondrejmirtes requested changes

2023-11-25 10:48 UTC, ondrejmirtes commented on src/Command/ErrorFormatter/JunitErrorFormatter.php
> -			'<testsuite failures="%d" name="phpstan" tests="%d" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/junit-team/junit5/r5.5.1/
Why do you remove this? Maybe it's important

2023-11-25 10:48 UTC, ondrejmirtes commented on tests/PHPStan/Command/ErrorFormatter/junit-schema.xsd
> -<?xml version="1.0" encoding="UTF-8" ?>
Maybe you can find a newer version of this schema that includes file and line?

2023-11-25 10:48 UTC, ondrejmirtes commented on src/Command/ErrorFormatter/JunitErrorFormatter.php
> +			$result .= sprintf(' file="%s"', $this->escape($fileName));
What about absolute vs. relative path to the file? Typically you don't want to print the whole absolute path, but trim the beginning. But I'm not sure what PHPUnit does and what tools that read the output expect.

Anyway, this is usually done with the help of `RelativePathHelper`. Check the other formatters.

2023-11-27 14:43 UTC, oadam commented
@ondrejmirtes I'm removing any mention of a XSD because there is no official schema.

PHPUnit does not have it in its output as well : https://github.com/sebastianbergmann/phpunit/blob/main/tests/end-to-end/logging/log-junit-to-file.phpt#L26

If I add the `RelativePathHelper`, would you be open to merge this even with the XSD removal ?

My objective is to add file and linenumber so that, in my private repo, I can better annotate failed pull requests with https://github.com/marketplace/actions/junit-report-action (it annotates PR with [annotations on offending lines](https://github.com/mikepenz/action-junit-report/blob/main/.github/images/annotated.png))

2023-11-27 14:59 UTC, oadam commented
I just realized that you have a github output format ! You can disregard this PR is removing the XSD seems too much

2023-11-27 16:21 UTC, ondrejmirtes commented
Yeah, PHPStan provides nice experience out of the box :) Thanks anyway.

2023-11-27 16:21 UTC, closed without merging