Update functionMap for `str_increment()` / `str_decrement()`
phpstan/phpstan-src pull request #2777
Opened 2023-11-25 21:57 UTC by zonuexe

Add types to [`str_increment()`](https://php.net/str_increment) and [`str_decrement()`](https://php.net/str_decrement) added in PHP 8.3.

This PR conflicts with https://github.com/phpstan/phpstan-src/pull/2776, but since there seem to be few use cases for incrementing a constant, it seems sufficient to support only functionMap.

2023-11-25 22:06 UTC, zonuexe commented on resources/functionMap.php
> +'str_decrement' => ['non-empty-string'],
Since `str_decrement('1')` returns "0", it is typed as `non-empty-string`. https://3v4l.org/dKARI#v8.3.0

2023-11-25 22:09 UTC, zonuexe commented on resources/functionMap.php
> +'str_increment' => ['non-falsy-string'],
Since `str_increment(-1)` is not accepted and never returns either `""` or `"0"`, it is typed as `non-falsy-string`. https://3v4l.org/59U2u#v8.3.0

2023-11-26 12:23 UTC, ondrejmirtes requested changes

2023-11-26 12:23 UTC, ondrejmirtes commented on resources/functionMap_php83delta.php
> +		'str_decrement' => ['non-empty-string'],
These signatures are wrong, the functions also have parameters.

2023-11-26 12:23 UTC, ondrejmirtes commented on resources/functionMetadata.php
> +	'json_validate' => ['hasSideEffects' => false],
Please see the top of this file - it's generated and should not be updated manually.

2023-11-26 13:17 UTC, ondrejmirtes requested changes

2023-11-26 13:17 UTC, ondrejmirtes commented on resources/functionMap_php83delta.php
> +		'str_increment' => ['non-falsy-string', 'string'=>'string'],
Only `non-empty-string` should be accepted here.

2023-11-26 13:17 UTC, ondrejmirtes requested changes
I see you removed the changes from functionMetadata, but you were supposed to add them to the `_original.php` file.

2023-11-26 13:36 UTC, zonuexe commented
I'm sorry, I fixed and pushed them.

2023-11-26 13:40 UTC, zonuexe commented
> ```
> Run shivammathur/setup-php@v2
> /usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh
>
> ==> Setup PHP
> ✗ PHP Could not setup PHP 8.3
> > Error: The process '/usr/bin/bash' failed with exit code [1](https://github.com/phpstan/phpstan-src/actions/runs/6995916125/job/19031233659?pr=2777#step:3:1)
> ```

2023-11-26 14:32 UTC, ondrejmirtes requested changes

2023-11-26 14:32 UTC, ondrejmirtes commented on bin/functionMetadata_original.php
> +	'json_validate' => ['hasSideEffects' => false],
Please run `bin/generate-function-metadata.php` and commit the result so that these changes have the right effect.

2023-11-26 14:45 UTC, zonuexe commented on bin/functionMetadata_original.php
> +	'json_validate' => ['hasSideEffects' => false],
Thank you for suggestion, I fixed, rebase and squashed.

2023-11-26 14:48 UTC, merged

2023-11-26 14:48 UTC, ondrejmirtes commented
Thank you.