Update functionMap
phpstan/phpstan-src pull request #2783
Opened 2023-11-26 18:18 UTC by zonuexe

2023-11-26 18:21 UTC, ondrejmirtes requested changes

2023-11-26 18:21 UTC, ondrejmirtes commented on resources/functionMap.php
> +'stream_socket_enable_crypto' => ['0|bool', 'stream'=>'resource', 'enable'=>'bool', 'crypto_method='=>'int', 'session_stream='=>'resource'],
Parameters don't need to be renamed

2023-11-26 18:21 UTC, ondrejmirtes commented on resources/functionMap.php
> +'getmxrr' => ['bool', 'hostname'=>'string', '&w_mxhosts'=>'list<string>', '&w_weight='=>'list<0, 65535>'],
What effect should this have? The types aren't enforced: https://phpstan.org/r/25c3b187-4888-4aa4-86ad-5e350f16346f

2023-11-26 18:35 UTC, zonuexe commented on resources/functionMap.php
> +'getmxrr' => ['bool', 'hostname'=>'string', '&w_mxhosts'=>'list<string>', '&w_weight='=>'list<0, 65535>'],
I see, it turns out that typing like `@param-out` cannot be solved by modifying only the functionMap.

https://phpstan.org/r/3c7a8a08-abce-45c9-b310-0bcb4e4b6ba4

The execution results of the function are as follows:

<img width="528" alt="スクリーンショット 2023-11-27 3 30 35" src="https://github.com/phpstan/phpstan-src/assets/822086/5e4be950-2fc7-492d-a2b4-22b8cc52d3b4">

2023-11-27 08:09 UTC, merged

2023-11-27 08:09 UTC, ondrejmirtes commented
Thank you!