Transform `if` / `else if` into flat `if` / `elseif` when possible
phpstan/phpstan-src pull request #2799
Opened 2023-11-30 19:05 UTC by herndlm

Closes https://github.com/phpstan/phpstan/issues/10113

Alternative to https://github.com/phpstan/phpstan-src/pull/2728

2023-11-30 19:40 UTC, herndlm commented
Looking good, but apparently I made Rector on Windows angry somehow?

2023-12-05 15:52 UTC, herndlm commented
any idea what the (rector) issue might be here? it kept happening after a rebase, I don't want to rebase unnecessarily. wonder if I need to bump some rector cache key?

2023-12-05 16:38 UTC, ondrejmirtes requested changes
Also: Please write a custom rule in `tests` that just verifies the AST is transformed as expected.

So it should hook onto `If_` and just report how many `elseifs` it sees.

The Rector issue might or might not be fixed by other suggestion :)

2023-12-05 16:38 UTC, ondrejmirtes commented on src/Parser/RichParser.php
> +		$nodeTraverser->addVisitor($transformElseIfToFlatElseIfVisitor);
I'm a bit surprised this works. I'm not sure about the order and effects the visitors are called in. I'd expect the other visitors not being able to see effects from this one.

I'd be a little bit calmer if the AST was transformed with `TransformElseIfToFlatElseIfVisitor` by a separate NodeTraverser and only after that it was passed to the current `$nodeTraverser`.

2023-12-09 20:58 UTC, herndlm commented
Got inspired by `CleaningParserTest` and ended up writing the test a bit different. WDYT?
Rector still doesn't like me here apparently :/

2023-12-18 13:14 UTC, herndlm commented
I believe this one is ready (for review) again. I was just waiting for you to switch to the simplified downgrader :)

2024-01-05 13:00 UTC, ondrejmirtes commented
The failures in Rector worry me a bit: https://github.com/phpstan/phpstan-src/actions/runs/7420725636/job/20192723240

2024-03-29 19:48 UTC, herndlm commented
I don't know Rector well enough but I guess the errors related to that if/else rector mean that the change here is not possible. Is https://github.com/phpstan/phpstan-src/pull/2728 a better alternative after all, maybe? Or something else? 🤔

2024-03-29 19:48 UTC, closed without merging