ResolvedPhpDocBlock: fix parent return tag merging
phpstan/phpstan-src pull request #2803
Opened 2023-12-05 11:43 UTC by janedbal

This should resolve https://github.com/phpstan/phpstan/issues/6462 and https://github.com/phpstan/phpstan-doctrine/pull/503

Current failure: https://phpstan.org/r/f8871cfa-7e74-48a3-854f-cb64495aabea

2023-12-05 12:18 UTC, ondrejmirtes approved these changes

2023-12-05 12:18 UTC, ondrejmirtes commented on src/PhpDoc/ResolvedPhpDocBlock.php
> +						return $type->changeBaseClass($classReflection);
Great, I'd fix this the same way so 👍 

I just hate adding new properties to this class but I didn't figure out a better solution. yet. Merging this.

2023-12-05 12:49 UTC, staabm commented
it seems the change fixes more stuff, see https://github.com/phpstan/phpstan-src/actions/runs/7100699219?pr=2803

2023-12-05 15:51 UTC, staabm commented
Regression tests for all fixed issues would be good. Sorry I did not mention it earlier

2023-12-05 15:55 UTC, janedbal commented
@staabm All those look the same. But we can add them to be sure..

2023-12-05 16:05 UTC, janedbal commented
@staabm Added

2023-12-05 16:34 UTC, ondrejmirtes requested changes

2023-12-05 16:34 UTC, ondrejmirtes commented on tests/PHPStan/Rules/Methods/MethodSignatureRuleTest.php
> +			__DIR__ . '/data/bug-3580.php',
I need separate test method for each of these files. Allowing passing multiple files into `analyse` method was a mistake and I eventually want to get rid of it. Thanks.

2023-12-06 08:35 UTC, janedbal commented on tests/PHPStan/Rules/Methods/MethodSignatureRuleTest.php
> +			__DIR__ . '/data/bug-3580.php',
Yeah, it felt weird, but I could instantly see 4 errors on 1.10.x instead of failing on first one.

Splitted.

2023-12-06 08:36 UTC, janedbal commented on tests/PHPStan/Rules/Methods/MethodSignatureRuleTest.php
> +			__DIR__ . '/data/bug-3580.php',
> I eventually want to get rid of it

What about emitting deprecation notice there?

2023-12-06 16:34 UTC, ondrejmirtes commented on tests/PHPStan/Rules/Methods/MethodSignatureRuleTest.php
> +			__DIR__ . '/data/bug-3580.php',
I'd accept removing a native type from the parameter and putting a `string` type in a bleeding-edge PHPDoc stub file for RuleTestCase :)

2023-12-06 16:35 UTC, ondrejmirtes requested changes

2023-12-06 16:35 UTC, ondrejmirtes commented on tests/PHPStan/Rules/Methods/MethodSignatureRuleTest.php
> +		$this->analyse([__DIR__ . '/data/bug-10208.php'], []);
One `analyse` call per PHPUnit `test` method please 😂  That way we learn all of them are wrong instead of one at a time.

2023-12-07 17:13 UTC, janedbal commented on tests/PHPStan/Rules/Methods/MethodSignatureRuleTest.php
> +		$this->analyse([__DIR__ . '/data/bug-10208.php'], []);
Oh god, some AI should read this and fix it instantly for me 😁

2023-12-08 08:55 UTC, janedbal commented on tests/PHPStan/Rules/Methods/MethodSignatureRuleTest.php
> +			__DIR__ . '/data/bug-3580.php',
Ok, that is for another MR for sure. Resolving this thread.

2023-12-08 08:57 UTC, janedbal commented on tests/PHPStan/Rules/Methods/MethodSignatureRuleTest.php
> +		$this->analyse([__DIR__ . '/data/bug-10208.php'], []);
Done

2023-12-08 13:47 UTC, merged

2023-12-08 13:47 UTC, ondrejmirtes commented
Thank you!