Fix check generic mixed type based on config v2
phpstan/phpstan-src pull request #2885
Opened 2024-01-21 16:01 UTC by schlndh

This is an alternative to https://github.com/phpstan/phpstan-src/pull/2809 . This time I was able to limit the changes to `RuleLevelHelper` (it kind of makes me wonder how I missed this option in the first place).

The goal is to handle `TemplateMixedType` similarly to explicit `MixedType` with respect to `checkExplicitMixed`. Here is an example of the issues in as many cases as I can think of https://phpstan.org/r/0b58afa8-fd01-4991-922e-d46037106135 . As you can see, even the regular mixed type is not covered completely, but that's a matter for another PR(s).

2024-01-21 16:06 UTC, schlndh commented on src/Rules/RuleLevelHelper.php
> +			if ($type instanceof TemplateMixedType && $this->checkExplicitMixed) {
`TemplateMixedType` extends explicit `MixedType`, so I made its behavior consistent with that.

I wonder whether `@template T` and `@template T of mixed` should be implicit/explicit respectively. But I assume that the implicit mixed exists mainly for untyped legacy code. So in that sense it seems right to me for both of them to be considered explicit, even though it feels slightly inconsistent with how it works for non-generic parameters. Especially, considering that `checkImplicitMixed` is off even with level 9.

2024-01-21 16:09 UTC, schlndh commented on tests/PHPStan/Rules/Methods/data/call-static-method-mixed.php
> +	 * @param callable(mixed): void $cb
Unfortunately, I wasn't able to figure out how to make a callable with implicit mixed parameter. But if it's impossible to make one, then it doesn't matter how it behaves and so there's no need to test it.

2024-01-21 16:10 UTC, schlndh commented on tests/PHPStan/Rules/Cast/InvalidCastRuleTest.php
> +		$explicitOnlyErrors = [
IMO it should report all casts (possible with the exception of `(bool)` cast). But I consider that out-of-scope for this PR.

2024-01-21 22:42 UTC, ondrejmirtes requested changes
Hi, I mostly like this, but I'd prefer the new behaviour only for bleeding edge, because this leads to more errors being eeported.

Please lead to the new behaviour only when `newRuleLevelHelper` is enabled, otherwise use the old behaviour. You don't need to test it, it should be obvious from the diff (that you're adding new branches to the code and otherwise not changing anything else).

2024-01-22 19:19 UTC, ondrejmirtes commented
I've reworked the code to show you what I meant - the diff is now obvious, and removing the feature flags when working on 2.0 will be trivial.

![Screenshot 2024-01-22 at 20 18 20](https://github.com/phpstan/phpstan-src/assets/104888/23c24fb8-4368-4a49-87bd-80e154432d76)
![Screenshot 2024-01-22 at 20 18 10](https://github.com/phpstan/phpstan-src/assets/104888/7743f24c-70e4-4862-aced-d491ffb6f8b0)

2024-01-22 19:19 UTC, ondrejmirtes commented
If the build passes  I'm gonna merge this :)

2024-01-22 19:29 UTC, ondrejmirtes approved these changes

2024-01-22 19:30 UTC, merged

2024-01-22 19:30 UTC, ondrejmirtes commented
Thank you!