Add always used method extension
phpstan/phpstan-src pull request #2927
Opened 2024-02-20 20:48 UTC by axlon

This PR adds a new extension type to PHPStan. This new extension type allows developers to tell PHPStan when a private method is used.

My personal use case:
I make use of a library that exposes a trait that dynamically calls methods on my objects, since I have no other uses for these methods I typically make them private. Since there are no direct references to these methods PHPStan reports them as unused.

I used #495 as a blueprint for this PR.

Lastly, one thing I'm somewhat unsure about is the positioning of the extension check within the rule, maybe moving it up or down somewhat could be beneficial to performance.

2024-03-12 16:00 UTC, axlon commented
@ondrejmirtes is this something you would consider adding to PHPStan? If something is missing or needs clarification please let me know, happy to look at it!

PS I noticed 2 actions are failing, but I don't know why or if it even related to this PR

2024-03-13 12:05 UTC, ondrejmirtes commented
@axlon Don't worry, I really like this PR, it's well thought-out, I just didn't have much time to look into this thorougly.

2024-03-20 10:07 UTC, ondrejmirtes requested changes
Besides one little thing this works for me :) Thank you!

2024-03-20 10:07 UTC, ondrejmirtes commented on src/Rules/Methods/AlwaysUsedMethodExtension.php
> +interface AlwaysUsedMethodExtension
This needs `@api` and also description similar to https://apiref.phpstan.org/1.11.x/source-src.PhpDoc.StubFilesExtension.html#5.

2024-03-20 21:45 UTC, merged

2024-03-20 21:45 UTC, ondrejmirtes commented
Perfect, thank you!

2024-03-21 09:34 UTC, thg2k commented
I like the use case, I ran into something similar in the past. But I was wondering: Wouldn't an annotation be more suitable for this job rather than a plugin type?

```php

/**
 * @phpstan-always-used
 */
private function my_method(): void {
}

```

2024-03-21 09:36 UTC, ondrejmirtes commented
> Wouldn't an annotation be more suitable for this job

You can write an annotation - an ignore annotation :)

The thing with extensions is that you can describe the logic generally. Instead of adding thousands of annotations in your code, you can write a single extension that describes the logic to mark the right methods as always used.

2024-03-21 09:46 UTC, thg2k commented
> You can write an annotation - an ignore annotation :)
> 

That's surely a solution, but it would ignore every possible error, not only the intended one. I think I solved with a ignoreErrors template in the config file, like a regexp ignoring all kind of private unused errors, targeting the specific directory where the problematic classes reside.

> The thing with extensions is that you can describe the logic generally. Instead of adding thousands of annotations in your code, you can write a single extension that describes the logic to mark the right methods as always used.

That's very true.

Thx!

2024-03-21 09:54 UTC, ondrejmirtes commented
> but it would ignore every possible error, not only the intended one

This is going to be solved in PHPStan 1.11 with error identifiers and new `@phpstan-ignore` tag. See: https://phpstan.org/user-guide/ignoring-errors#ignoring-in-code-using-phpdocs