Error on references of PHPStan internal class names
phpstan/phpstan-src pull request #2932
Opened 2024-02-22 16:17 UTC by staabm

As discussed in https://github.com/phpstan/phpstan/issues/10587#issuecomment-1956826459 this PR adds a new `ClassForbiddenNameCheck` which reports errors when code references a PHPStan prefixed class from a phpstan.phar file

2024-02-22 17:19 UTC, staabm commented
Similar problems can happen on other popular tools, e.g. Rector. 
Should we also hardcode a rector prefix?

2024-02-22 18:41 UTC, ondrejmirtes commented
Thank you, I love this!

I wonder if we could detect it automatically but then we're in the https://github.com/shipmonk-rnd/composer-dependency-analyser area so probably not worth it.

I'd hardcode:

* PHPStan prefix
* Rector prefix
* The default PHP-Scoper prefix (https://github.com/humbug/php-scoper) - please research what it is.

2024-02-22 19:42 UTC, staabm commented
Added support for rector

https://github.com/rectorphp/rector-src/blob/f5a45a5aeb6e5e1264d546e55dbd8880046b36ce/scoper.php#L31

… and php-scoper

https://github.com/humbug/php-scoper/blob/cd909d4bb53e6668a0284fea08458428c28af697/src/Configuration/ConfigurationFactory.php#L427C17-L427C27

2024-02-23 10:04 UTC, ondrejmirtes requested changes

2024-02-23 10:04 UTC, ondrejmirtes commented on src/Rules/ClassNameCheck.php
> +			$errors += $this->classCaseSensitivityCheck->checkClassNames($pairs);
I don't really like doing `+` here. I'd rather iterate over the array and add the error one-by-one with `$errors[] = ...`.

2024-02-23 10:04 UTC, ondrejmirtes commented on src/Rules/ClassForbiddenNameCheck.php
> +			))->line($pair->getNode()->getLine())->build();
Should be non-ignorable.

2024-02-23 10:04 UTC, ondrejmirtes commented on src/Rules/ClassForbiddenNameCheck.php
> +				'Internal %s Class cannot be referenced: %s.',
Please rewrite this as: "Referencing prefixed PHPStan class: _PHPStan_d5242a5\Symfony/Finder"

And add a tip without the prefix: "This is most likely unintentional. Did you mean to type Symfony\Finder?"

2024-02-23 10:45 UTC, merged

2024-02-23 10:45 UTC, ondrejmirtes commented
Thank you!