Add support for constructor assertions
phpstan/phpstan-src pull request #2950
Opened 2024-02-29 17:14 UTC by axlon

Enables the following:

```php
class Person
{
    /** @phpstan-assert non-empty-string $firstName */
    public function __construct(string $firstName) {}
}

$person = new Person($firstName);
// $firstName can no longer be empty
```

Fixes https://github.com/phpstan/phpstan/issues/10645 (partially)

2024-02-29 17:23 UTC, ondrejmirtes requested changes
What do you mean by "partially"?

2024-02-29 17:23 UTC, ondrejmirtes commented on tests/PHPStan/Analyser/data/assert-constructor.php
> +/**
Move this into anonymous function and use a string parameter coming into the function.

2024-02-29 17:28 UTC, axlon commented
> What do you mean by "partially"?

@ondrejmirtes This PR currently does not tackle assertions on promoted properties, so for example:

```php
class Person
{
    /** @phpstan-assert non-empty-string $this->firstName */
    public function __construct(public string $firstName) {}
}

$person = new Person($firstName);
dumpType($person->firstName); // non-empty-string
```

I'm working on this as well but it needs a little more time

2024-02-29 17:54 UTC, ondrejmirtes commented
This use case does not make sense to me, you can type the property to be non-empty-string from the start, no need to assert it.

2024-02-29 18:34 UTC, axlon commented
The use case is being able to annotate promoted props to be a narrowed version of the variable going in.

Essential this, but with promoted props:

```php
class Person
{
    /**
     * @var non-empty-string
     */
    public string $firstName;

    public function __construct(string $firstName)
    {
        assert($firstName !== '');
        $this->firstName = $firstName;
    }
}
```

I am aware I could also annotate the class with `@property` as well, so its not really a big deal of asserting `$this->firstName` from a constructor is a no go 👍

2024-03-01 07:42 UTC, ondrejmirtes approved these changes

2024-03-01 07:42 UTC, merged

2024-03-01 07:42 UTC, ondrejmirtes commented
Thank you!