Introduce ForbiddenClassNameExtension for append additional forbidden…
phpstan/phpstan-src pull request #2979
Opened 2024-03-19 12:01 UTC by kamil-zacek

… class prefixes

2024-03-19 12:11 UTC, staabm commented
Could you give us an idea what your use-case is?

Is it php-scoper related or something completely different?

2024-03-19 12:24 UTC, ondrejmirtes commented
@staabm This was discussed outside of GitHub. The idea is that you want to report usages of classes that you're not supposed to use in application. For example: Generated Doctrine proxies from their configured namespace.

2024-03-19 12:27 UTC, ondrejmirtes requested changes
The only other problem is that this isn't tested. Please create a new RuleTestCase for one of the rules affected by this, add an example new neon file with a new extension implementing this interface, and reference it in `public static function getAdditionalConfigFiles()` in that test case. That way this extension will be added to the container.

2024-03-19 12:27 UTC, ondrejmirtes commented on src/Classes/ForbiddenClassNameExtension.php
> +interface ForbiddenClassNameExtension
Please put `@api` here and explanation what it is for and how to register it. Example: https://apiref.phpstan.org/1.11.x/source-src.PhpDoc.StubFilesExtension.html#5

2024-03-20 08:32 UTC, ondrejmirtes approved these changes

2024-03-20 08:32 UTC, ondrejmirtes commented
Perfect, thank you!

2024-03-20 08:32 UTC, merged