Fix fatal error on `constant('')`
phpstan/phpstan-src pull request #3013
Opened 2024-04-12 19:12 UTC by staabm

closes https://github.com/phpstan/phpstan/issues/10867

2024-04-12 19:27 UTC, ondrejmirtes requested changes
I'd like to have a stub for Name constructor and all Name subclasses constructors that enforces non-empty-string.

2024-04-12 20:30 UTC, staabm commented
using non-empty-string names everywhere would spread across the whole codebase. I fixed the places which worked without ugly catches and baselined the remaining ones

2024-04-12 20:35 UTC, staabm commented
tested locally with

```
➜  phpstan-src git:(bug10867) ✗ cat test4.php 
<?php

$n = new \PhpParser\Node\Name('');

$r = new \PhpParser\Node\Name\Relative('');

$fq = new \PhpParser\Node\Name\FullyQualified('');
➜  phpstan-src git:(bug10867) ✗ php bin/phpstan analyze test4.php --debug
Note: Using configuration file /Users/staabm/workspace/phpstan-src/phpstan.neon.dist.
/Users/staabm/workspace/phpstan-src/test4.php
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------ 
  Line   test4.php                                                                                                                                                   
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------ 
  3      Parameter #1 $name of class PhpParser\Node\Name constructor expects non-empty-array<string>|PhpParser\Node\Name|non-empty-string, '' given.                 
         💡 Type #1 from the union: '' is empty.                                                                                                                     
  5      Parameter #1 $name of class PhpParser\Node\Name\Relative constructor expects non-empty-array<string>|PhpParser\Node\Name|non-empty-string, '' given.        
         💡 Type #1 from the union: '' is empty.                                                                                                                     
  7      Parameter #1 $name of class PhpParser\Node\Name\FullyQualified constructor expects non-empty-array<string>|PhpParser\Node\Name|non-empty-string, '' given.  
         💡 Type #1 from the union: '' is empty.                                                                                                                     
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------ 


                                                                                                                        
 [ERROR] Found 3 errors                                                                                                 
                                                                                                                        
```

2024-04-12 20:39 UTC, ondrejmirtes commented
> using non-empty-string names everywhere would spread across the whole codebase.

Yes, that's the idea. I'm not looking for a quick fix but a correct fix. Please do not baseline anything. Baseline is not supposed to grow.

2024-04-13 06:42 UTC, staabm commented
looks like this will be a breaking change and can only be merged for 2.0?
should the crash fix be separated?

2024-04-14 13:26 UTC, ondrejmirtes requested changes
Please be more careful - in some places where we gain type safety thanks to the new PHPDocs, you instantly throw it away by throwing `ShouldNotHappenException`.

2024-04-14 13:26 UTC, ondrejmirtes commented on conf/config.neon
> +		- ../stubs/PhpParserName.stub
Please register this stub only in `build/phpstan.neon`. It's only for internal PHPStan purposes.

2024-04-14 13:26 UTC, ondrejmirtes commented on conf/config.neon
> +		- ../stubs/PhpParserName.stub
And move the stub elsewhere, probably to `build/stubs`.

2024-04-14 13:26 UTC, ondrejmirtes commented on src/Type/Php/ArrayFilterFunctionReturnTypeReturnTypeExtension.php
> +			if ($fqcn === '') {
You can definitely write some userland code that will execute this condition

2024-04-14 13:26 UTC, ondrejmirtes commented on src/Type/Php/ArrayFilterFunctionReturnTypeReturnTypeExtension.php
> +			throw new ShouldNotHappenException();
You can definitely write some userland code that will execute this condition

2024-04-14 13:26 UTC, ondrejmirtes commented on src/Type/Php/ConstantHelper.php
> +				throw new ShouldNotHappenException();
What if you can `constant('::aa')`? That will execute this condition

2024-04-14 13:26 UTC, ondrejmirtes commented on src/Rules/Generics/TemplateTypeCheck.php
> +			if ($templateTag->getName() === '') {
This should be tackled in TemplateTag by typehinting `non-empty-string`.

2024-04-14 13:26 UTC, ondrejmirtes commented on src/Reflection/InitializerExprContext.php
> +			throw new ShouldNotHappenException('Namespace cannot be empty.');
This could be tackled by a better typehint in BetterReflection.

2024-05-31 08:44 UTC, ondrejmirtes commented
It'd be great if you could finish this one. Thanks.

2024-05-31 08:46 UTC, staabm commented
I am on it right in this moment :)

2024-05-31 09:46 UTC, staabm commented on src/Reflection/InitializerExprContext.php
> +			throw new ShouldNotHappenException('Namespace cannot be empty.');
fix in https://github.com/Roave/BetterReflection/pull/1428

2024-05-31 09:56 UTC, staabm commented
I think this one is ready to land. the last remaining error should be fixed with https://github.com/Roave/BetterReflection/pull/1428

2024-05-31 13:31 UTC, merged

2024-05-31 13:31 UTC, ondrejmirtes commented
Thank you!

2024-05-31 16:53 UTC, staabm commented on build/stubs/PhpParserName.stub
> +class Name extends NodeAbstract
we should be able to remove this stub after the next php-parser release because of https://github.com/nikic/PHP-Parser/pull/993