Check array key type in PHPdoc
phpstan/phpstan-src pull request #303
Opened 2020-08-20 12:56 UTC by leongersen

A take at #3753. I couldn't find an existing way to retain the original type information in a `NeverType`, but it helps the clarity of the error message. An alternative would be to check the type in `InvalidPhpDocVarTagTypeRule`, instead of in `TypeNodeResolver`.

2020-08-20 13:02 UTC, ondrejmirtes commented
Hi, please read my instructions at https://github.com/phpstan/phpstan/issues/3753#issuecomment-677632772 more carefully and follow them.

1) we need to `TypeCombinator::intersect()` the key [here](https://github.com/phpstan/phpstan-src/blob/2335152861184bb0d3fc3562d24b07728c4c2c48/src/PhpDoc/TypeNodeResolver.php#L313) with `new UnionType([new IntegerType(), new StringType()])`
2) implement recursive checking for ErrorType/NeverType using TypeTraverser [in this rule](https://github.com/phpstan/phpstan-src/blob/2335152861184bb0d3fc3562d24b07728c4c2c48/src/Rules/PhpDoc/InvalidPhpDocVarTagTypeRule.php#L96-L102) and others

This PR cannot be accepted because the code is different and doesn't behave as we want it to.

2020-08-20 13:23 UTC, leongersen commented
@ondrejmirtes Could you give a hint on how the original type would be infered from the `NeverType` (so that it can be used in the error message)?

2020-08-20 13:28 UTC, ondrejmirtes commented
That's out of scope of this PR and too hard. I simply want to achieve this error message: https://phpstan.org/r/ab5ad711-5186-4fae-a52a-3cb4106892c1

Improving this error message would be something for another time and a major version.

2020-08-20 15:00 UTC, leongersen commented
Ok, that's clear. I've applied your suggestions and added support for `@param` and `@return`.

2020-08-20 15:11 UTC, ondrejmirtes requested changes

2020-08-20 15:11 UTC, ondrejmirtes commented on src/Type/TypeTraverserHelper.php
> +	public static function reduceToUnresolveableType(Type $baseType): Type
I imagined something like `hasUnresolvableType(Type $type): bool` instead.

2020-08-20 15:11 UTC, ondrejmirtes commented on src/Rules/PhpDoc/InvalidPhpDocVarTagTypeRule.php
> +			$varTagType = TypeTraverserHelper::reduceToUnresolveableType($varTagType);
The same logic should be applied in IncompatiblePropertyPhpDocTypeRule as well.

2020-08-21 08:01 UTC, leongersen commented
@ondrejmirtes What would you like me to do with the failing tests in `NodeScopeResolverTest`? 

For example, for the type `array<TKey, TValue> $iterator`, the added intersection result in the following change:

```
-'array<TKey (method Bug3266\Foo::iteratorToArray(), argument), TValue (method Bug3266\Foo::iteratorToArray(), argument)>'
+'array<(int&TKey (method Bug3266\Foo::iteratorToArray(), argument))|(string&TKey (method Bug3266\Foo::iteratorToArray(), argument)), TValue (method Bug3266\Foo::iteratorToArray(), argument)>'
```

Which is correct, but I don't know if changing this output is desirable?

2020-08-25 15:07 UTC, ondrejmirtes commented
@leongersen I think I want `array<mixed, X>` to keep the `mixed` untouched, which will also fix the template type issue.

2020-08-26 07:16 UTC, leongersen commented
Sorry, I don't really understand what you mean. Are you saying to check if the array key type is a supertype of the `mixed` type?  

Also, would you mind elaborating on why checking whether `int|string`->accepts() the array key type is not a valid solution here? I'm guessing I'm misunderstanding what `accepts` is for.

2021-06-08 10:56 UTC, ondrejmirtes commented
Superseded by https://github.com/phpstan/phpstan-src/commit/1de5de80ecb02255251ee0324801c56ac30a1943

2021-06-08 10:56 UTC, closed without merging