Function containing inlineHtml has side-effects
phpstan/phpstan-src pull request #3072
Opened 2024-05-13 08:30 UTC by staabm

closes https://github.com/phpstan/phpstan/issues/10998

2024-05-13 13:30 UTC, ondrejmirtes requested changes

2024-05-13 13:30 UTC, ondrejmirtes commented on src/Analyser/NodeScopeResolver.php
> +				new ImpurePoint($scope, $stmt, 'inlineHtml', 'inlineHtml', true),
Please test the error message when this is done inside `@phpstan-pure` function. It should be nicer than `inlineHtml`.

I'd even say that the identifier should be renamed to something like `betweenPhpTags` or something.

2024-05-13 14:15 UTC, staabm commented on src/Analyser/NodeScopeResolver.php
> +				new ImpurePoint($scope, $stmt, 'inlineHtml', 'inlineHtml', true),
I did not realize these strings are taken into the rule error message.

I still have to learn the new classes and their implications :)

2024-05-14 12:08 UTC, merged

2024-05-14 12:08 UTC, ondrejmirtes commented
Thank you.