Conditional return type for `SQLite3Result::fetchArray()`
phpstan/phpstan-src pull request #3080
Opened 2024-05-16 10:08 UTC by devnix

I'm aware that this change can be wrong or incomplete. I was wondering if there is a way in this project to do types for tests, for example https://github.com/azjezz/psl/blob/next/tests/static-analysis

2024-05-16 10:46 UTC, ondrejmirtes commented
You mean tests for types? Sure: https://phpstan.org/developing-extensions/testing#type-inference

Here most of them are in NodeScopeResolverTest.

2026-04-25 21:56 UTC, VincentLanglet commented
Hi @devnix, are you still interested by this PR ? If so, please now target 2.1.x instead. Thanks

2026-04-30 07:01 UTC, staabm commented on resources/functionMap.php
> +'SQLite3Result::fetchArray' => ['($mode is SQLITE3_NUM ? non-empty-list<mixed>|false : ($mode is SQLITE3_ASSOC ? non-empty-array<string,mixed>|false : false))', 'mode='=>'int'],
its the first "conditional return type"-style signature in this file.
I think we should add a nsrt test to make sure it actually works

2026-04-30 07:48 UTC, VincentLanglet reviewed
Is a similar return type possible for `fetchAll` ?
https://github.com/JetBrains/phpstorm-stubs/blob/34a487bd374e42f4ce58606473d1b6882bfec2b7/sqlite3/sqlite3.php#L642
(will need to be in php85delta since it was introduced in php 8.5).

Also might be worth to add fetchArray has having sideEffect to avoid something like 
https://phpstan.org/r/7281fb29-1861-4297-8c50-4a708cbebf1c

2026-04-30 14:05 UTC, devnix commented
> Is a similar return type possible for `fetchAll` ? https://github.com/JetBrains/phpstorm-stubs/blob/34a487bd374e42f4ce58606473d1b6882bfec2b7/sqlite3/sqlite3.php#L642 (will need to be in php85delta since it was introduced in php 8.5).
> 
> Also might be worth to add fetchArray has having sideEffect to avoid something like https://phpstan.org/r/7281fb29-1861-4297-8c50-4a708cbebf1c

Great catch @VincentLanglet, done!

2026-04-30 14:08 UTC, VincentLanglet approved these changes

2026-04-30 14:09 UTC, VincentLanglet requested changes

2026-04-30 14:09 UTC, VincentLanglet commented on tests/PHPStan/Analyser/nsrt/sqlite3-result-fetch-all-php85.php
> +<?php // php >= 8.5
```suggestion
<?php // lint >= 8.5
```

2026-04-30 14:34 UTC, devnix commented on tests/PHPStan/Analyser/nsrt/sqlite3-result-fetch-all-php85.php
> +<?php // php >= 8.5
Sorry, fixed 🤦🏼‍♂️

2026-04-30 15:25 UTC, VincentLanglet approved these changes

2026-05-01 07:01 UTC, staabm approved these changes

2026-05-01 07:01 UTC, staabm commented
thank you

2026-05-01 07:01 UTC, merged