make assigning property via reference impure
phpstan/phpstan-src pull request #3082
Opened 2024-05-17 12:21 UTC by schlndh

Fixes https://phpstan.org/r/cbe5c7f9-f5bd-4101-8cf6-37b7732946d4

I set `certain = false`, because theoretically the referenced variable may already be set, and the reference may never be written. In which case it would be pure. But I can't imagine why the reference would be used in such a way in the first place.

2024-05-17 12:45 UTC, staabm commented on tests/PHPStan/Rules/Pure/data/impure-assign-ref.php
> +
I thnk you are missing `NullsafePropertyFetch` variants

```suggestion
```
	private function bar7(?self $other): void
	{
		$value = &$other?->value;
		$value = 1;
	}
```
```

2024-05-18 08:27 UTC, ondrejmirtes requested changes

2024-05-18 08:27 UTC, ondrejmirtes commented on src/Analyser/NodeScopeResolver.php
> +								'propertyAssign',
I think this should be a new identifier. Something like `propertyAssignByRef` or something.

2024-05-18 09:06 UTC, ondrejmirtes requested changes

2024-05-18 09:06 UTC, ondrejmirtes commented on src/Analyser/NodeScopeResolver.php
> +								'property assignment by reference',
This deserves a test :) In PureFunctionRule or PureMethodRule.

2024-05-18 09:07 UTC, ondrejmirtes commented on src/Analyser/NodeScopeResolver.php
> +								'property assignment by reference',
Meaning: test the scenario where this error message is shown.

2024-05-30 14:24 UTC, ondrejmirtes requested changes

2024-05-30 14:24 UTC, ondrejmirtes commented on src/Analyser/NodeScopeResolver.php
> +								false,
Should be `true`, right? There isn't a case where this might still be pure.

2024-05-30 14:36 UTC, schlndh commented on src/Analyser/NodeScopeResolver.php
> +								false,
It could be pure:

> I set certain = false, because theoretically the referenced variable may already be set, and the reference may never be written. In which case it would be pure. But I can't imagine why the reference would be used in such a way in the first place.

```php
<?php

class Foo
{
    public ?int $foo;
    
    public function bar(): void
    {
        $x = &$this->foo;
    }
}

$foo = new Foo;
$foo->foo = 5;
$foo->bar();
var_dump($foo->foo);
```

2024-05-30 14:58 UTC, ondrejmirtes commented on src/Analyser/NodeScopeResolver.php
> +								false,
Alright, cool :)

2024-05-30 14:58 UTC, merged

2024-05-30 14:58 UTC, ondrejmirtes commented
Thank you!