Solve identical comparison with local-variance
phpstan/phpstan-src pull request #3153
Opened 2024-06-12 13:34 UTC by VincentLanglet

Close https://github.com/phpstan/phpstan/issues/11161

2024-06-12 14:52 UTC, staabm commented
Issue-bot reported this seem to fix also another issue: https://github.com/phpstan/phpstan-src/actions/runs/9484392325

2024-06-12 19:39 UTC, ondrejmirtes requested changes
Yeah, that regression test too please.

2024-06-12 19:39 UTC, ondrejmirtes commented on src/Reflection/InitializerExprTypeResolver.php
> +		$isLeftSuperset = $leftType->isSuperTypeOf($rightType);
SuperType, not Superset

2024-06-12 21:39 UTC, VincentLanglet commented
> Yeah, that regression test too please.

Done

2024-06-17 15:03 UTC, merged

2024-06-17 15:03 UTC, ondrejmirtes commented
Thank you!