Improve `sprintf` return type inference
phpstan/phpstan-src pull request #3168
Opened 2024-06-19 09:51 UTC by staabm

2024-06-19 10:18 UTC, staabm commented on tests/PHPStan/Analyser/nsrt/bug-7387.php
> +		assertType('non-falsy-string&numeric-string', sprintf('%10$14F', $mixed, $s));
after https://github.com/phpstan/phpstan-src/pull/3126 is merged we have the necessary `PrintfHelper` to decide about the invalid number of arguments/placeholders

2024-06-19 13:36 UTC, staabm commented on src/Type/Php/SprintfFunctionDynamicReturnTypeExtension.php
> +			if ($argType->toString()->isNonFalsyString()->yes()) {
requires https://github.com/phpstan/phpstan-src/pull/3170

2024-06-20 07:44 UTC, staabm commented
the composer error is valid, as we previously inferred a non-empty-string return type, even though the sprintf pattern is not known at static analysis time.

other errors are the same ones are unrelated

2024-06-22 07:00 UTC, staabm commented
the reported phpstan error is interesstig.. it seems - depending on some unknown factor - reports that we are catching a non-throwable but ignoring this very same error by identifer leads to a "No error with identifier catch.notThrowable is reported on line 200."

(its unrelated to this PR though)

2024-06-22 07:09 UTC, staabm commented
I think its related to this `Consistency::flexEntity` call in the exception classes.. some class-alias stuff is going on there.. this might lead to a race condition depending on the order which classes will be scanned when

2024-06-22 07:27 UTC, ondrejmirtes commented
There's an opportunity to grab the code from Hoa packages and make a small single modern library with no magic and simple PSR-4 autoloading and replace Hoa in phpstan-src. I might look into it this summer.

2024-06-22 13:00 UTC, staabm commented
> I might look into it this summer.

ok, what can we do to fix the build until then?

2024-06-24 13:21 UTC, ondrejmirtes commented
Try to rebase on top of: https://github.com/phpstan/phpstan-src/commit/323315554048a22e6c01d635d6c5bb68f10d5aa1

2024-06-24 13:38 UTC, staabm commented
> Try to rebase on top of: [3233155](https://github.com/phpstan/phpstan-src/commit/323315554048a22e6c01d635d6c5bb68f10d5aa1)

looks great, thanks

2024-06-25 11:52 UTC, ondrejmirtes requested changes
I'm sorry. I see the diff of `src/Type/Php/SprintfFunctionDynamicReturnTypeExtension.php` and my brain just freezes. I'm not able to review this. Can you do this in smaller steps, or maybe not move that many things around?

"Make the change easy, then make the easy change."

2024-07-05 09:44 UTC, closed without merging