Simplify SprintfFunctionDynamicReturnTypeExtension
phpstan/phpstan-src pull request #3188
Opened 2024-06-25 13:19 UTC by staabm

extracted from github.com/phpstan/phpstan-src/pull/3168

2024-06-25 13:29 UTC, staabm commented on src/Type/Php/SprintfFunctionDynamicReturnTypeExtension.php
> -		if (count($formatType->getConstantStrings()) > 0) {
the loop is the same as before, just the if statement was unwrapped

2024-06-25 13:38 UTC, staabm commented
the new composer/composer errors are valid because the typing before this PR was too precise.

we can't know whether `sprintf` will return `non-empty-string` in a scenario where the format-pattern is a non-constant variable.
https://github.com/composer/composer/blob/776ff2ea51bfa83335b14fa9a85fab5fc7d35050/src/Composer/Package/BasePackage.php#L256
https://github.com/composer/composer/blob/776ff2ea51bfa83335b14fa9a85fab5fc7d35050/src/Composer/Package/BasePackage.php#L275

2024-06-25 13:47 UTC, ondrejmirtes requested changes

2024-06-25 13:47 UTC, ondrejmirtes commented on src/Type/Php/SprintfFunctionDynamicReturnTypeExtension.php
> +			&& count($args) === 2
Please add some tests in case when there is `$arg->unpack === true` involved.

2024-06-25 13:47 UTC, ondrejmirtes commented on src/Type/Php/SprintfFunctionDynamicReturnTypeExtension.php
> +			return null;
We know what would happen so we could be more precise: https://3v4l.org/DeSsG

2024-06-25 14:24 UTC, staabm commented on tests/PHPStan/Analyser/nsrt/non-falsy-string.php
> +		assertType("non-falsy-string", sprintf('%s', ...$arr)); // should be 'string'
the wrong `non-falsy-string` types will be fixed after we integrated the remaining parts of https://github.com/phpstan/phpstan-src/pull/3168

2024-06-26 12:09 UTC, merged

2024-06-26 12:09 UTC, ondrejmirtes commented
Thank you.

2024-06-26 12:25 UTC, ondrejmirtes commented
Hey, if I have `sprintf($nonEmptyString, $alsoNonEmptyString)`, why the inferred type isn't `non-empty-string`?

2024-06-26 13:22 UTC, herndlm commented
@staabm how do you find the time to work so  much on PHPStan. I'm doing something wrong 😅 recently too busy and I do lack motivation to work on it at night..