Allow overriding the PHP 7.2 support for PREG_UNMATCHED_AS_NULL
phpstan/phpstan-src pull request #3226
Opened 2024-07-11 13:47 UTC by Seldaek

cc @staabm 

I am not sure if this is too ugly or too specific for you to care, but in composer/pcre I did [build a compat layer](https://github.com/composer/pcre/blob/2.x/src/Preg.php#L429-L440) for PCRE_UNMATCHED_AS_NULL on PHP 7.2/7.3 - so it would be nice if I could enable this flag to get proper return types even on PHP 7.2/7.3

If it's too ugly I understand, and I'll live with it until Composer can drop 7.2 :)

2024-07-11 14:13 UTC, staabm commented
I agree having impl specific feature toggles in phpstan-src looks fishy. lets see what ondrey thinks about it

2024-07-11 14:15 UTC, Seldaek commented
Yeah, I guess alternatively I could simply copy the code in composer/pcre 2.x, it's not that much and shouldn't change too often once stabilized

2024-07-11 14:19 UTC, staabm commented
> Edit: that might allow me to remove the conflict on older phpstan too I guess as a bonus..

the array shape matches alone does not give you support in older phpstan-src versions. there are a few more parts - like the new `*ParameterOutTypeExtension` which is required.

2024-07-12 09:55 UTC, staabm commented
just alternative suggestion: instead of adding a new bool flag to the api, we might consider adding a new feature flag config switch in the .neon file

please don't adjust the PR until ondrej gave some insight though.

2024-07-12 11:06 UTC, ondrejmirtes requested changes
I'm mostly in favour of this, but what about a custom flag that would be a public constant in RegexArrayShapeMatcher and that would be passed into `int $flags`? We just need to make sure we're not conflicting with existing PCRE flags.

2024-07-12 11:37 UTC, Seldaek commented
Yeah that's a great idea to avoid polluting the arg list, I'll investigate.

2024-07-12 12:24 UTC, Seldaek commented
Ok I think that's what you meant?

2024-07-12 12:26 UTC, staabm commented
the phpdoc type needs a fix:

`* @param int-mask<PREG_OFFSET_CAPTURE|PREG_UNMATCHED_AS_NULL>|null $flags`

2024-07-12 14:06 UTC, Seldaek commented on src/Type/Php/RegexArrayShapeMatcher.php
> +	public const PREG_UNMATCHED_AS_NULL_ON_72_73 = 2048;
The highest in use currently is 256, so I chose 2048 to leave 512/1024 as gaps if PHP should add new constants there.

2024-07-12 14:40 UTC, Seldaek commented on src/Type/Php/RegexArrayShapeMatcher.php
> +			$flags = $flagsType->getValue() & (PREG_OFFSET_CAPTURE | PREG_UNMATCHED_AS_NULL | self::PREG_UNMATCHED_AS_NULL_ON_72_73);
Somehow phpstan thinks it's an `int<0, 2816>` as that's the value on the right. Could be nice if it was smarter here but I guess bitwise use is rare enough that it's not worth that much time spent optimizing for them.

The var annotation fixed it though.

2024-07-12 18:00 UTC, merged

2024-07-12 18:00 UTC, ondrejmirtes commented
Thank you!

2024-07-13 11:22 UTC, Seldaek commented
Cool, implemented in https://github.com/composer/pcre/pull/29/commits/088f7529930ba6d04c7a06cb3e32861f7485a800 and it works great!