Support literal strings in RegexGroupParser
phpstan/phpstan-src pull request #3284
Opened 2024-08-04 05:54 UTC by staabm

by detecting static string literals in the regex pattern, we make constant-array result-types of the [patterns more different](https://github.com/phpstan/phpstan/issues/11443#issuecomment-2266709936).
this helps the TypeCombinator to produce tagged unions more often, which can result in more precise overall types.

refs https://github.com/phpstan/phpstan/issues/11443

2024-08-04 07:09 UTC, staabm commented
phpstan-nette needs some expectation adjustments after merge. I will work on it after this one landed.

2024-08-04 07:21 UTC, ondrejmirtes requested changes

2024-08-04 07:21 UTC, ondrejmirtes commented on src/Type/Php/RegexGroupParser.php
> +		bool $repeatedMoreThenOnce,
Than

2024-08-04 07:32 UTC, merged

2024-08-04 07:32 UTC, ondrejmirtes commented
This is becoming ridiculously good! Thank you.

2024-08-04 21:25 UTC, Seldaek commented
Woah this is awesome! Makes me kinda want to handle foo? as 'fo'|'foo' for example.. And even character classes with very few possible outcomes could be done that way like [abc] can just be one of those 3.. Not sure if it'd bring enough value but as a regex nerd it just sounds cool. This may need to be forked as a regex static analysis lib tho 😅 I'm only half kidding this is getting so advanced it feels sad that it's not reusable by others.

2024-08-05 05:50 UTC, staabm commented
@Seldaek character classes have already been implemented with https://github.com/phpstan/phpstan-src/pull/3285

> this is getting so advanced it feels sad that it's not reusable by others.

The current impl is tightly coupled with the PHPStan type-system. Its not that easy to be reused. 

I think we need a concrete use-case to see whether re-using can make sense.

2024-08-05 12:41 UTC, Seldaek commented
Damn you've been on fire these last few days. I'm on vacation so haven't kept track too closely.

2024-08-05 14:12 UTC, mvorisek commented on src/Type/Php/RegexGroupParser.php
> +use function implode;
there is some issue - https://phpstan.org/r/78e9a062-ad8b-4a3d-a944-e671a4f17a9d - index `1` is optional, ie. the type is missing `|array{string}`

wider repro - https://phpstan.org/r/89288a2e-96e9-4c48-8419-3adc807bea74 - the last type is wrong too, the `1` and `2` indexes are definitely not present when index `3` is

2024-08-05 18:10 UTC, staabm commented on src/Type/Php/RegexGroupParser.php
> +use function implode;
Index 1/2 is present but empty when 3 exists: https://3v4l.org/VgCUJ

I agree there is a constant type peoblem though

2024-08-05 18:44 UTC, mvorisek commented on src/Type/Php/RegexGroupParser.php
> +use function implode;
> the last type is wrong too, the `1` and `2` indexes are definitely not present when index `3` is

sorry, I meant empty string of course

the 2nd repro would be best fixed by "conditional types", ie. like if the inner capturing group type were dependent on the outer capturing group type

2024-08-06 06:43 UTC, staabm commented on src/Type/Php/RegexGroupParser.php
> +use function implode;
please open issues with reproducing snippets for the known problems. there are too many open todos in already-merged PRs and I can't keep track of all of them