Narrow array on count(), string on strlen() with positive-int
phpstan/phpstan-src pull request #3373
Opened 2024-08-30 11:23 UTC by staabm

closes https://github.com/phpstan/phpstan/issues/11558

2024-08-30 11:27 UTC, staabm commented on src/Analyser/TypeSpecifier.php
> -		if (
moved this 2 if-blocks out of `specifyTypesForConstantBinaryExpression` as we no longer check for a constant type operand, but do a more general `isInteger` based handling, which includes unbound `IntegerRangeType`.

2024-08-30 11:28 UTC, staabm commented on src/Analyser/TypeSpecifier.php
> +			} elseif ($type->isConstantArray()->yes()) {
compensated the no

2024-08-30 11:30 UTC, staabm commented on tests/PHPStan/Analyser/nsrt/count-type.php
> +			assertType('array', $arr);
I think I did a mistake here in previous PRs, as the array can still be empty in the else branch

2024-09-02 17:31 UTC, ondrejmirtes requested changes
Too many changes. I can't read that diff. Please send this in smaller chunks.

2024-09-06 06:14 UTC, closed without merging