Fix setting offset to a List
phpstan/phpstan-src pull request #3382
Opened 2024-09-01 13:34 UTC by VincentLanglet

Extracted from https://github.com/phpstan/phpstan-src/pull/3381

2024-09-01 13:35 UTC, VincentLanglet commented on tests/PHPStan/Analyser/nsrt/array-is-list-offset.php
> +		assertType('true', array_is_list($array));
Prior to this PR, it was considered as false.

2024-09-01 17:14 UTC, ondrejmirtes requested changes
Hey, I specifically asked for ConstantArrayTypeBuilderTest reproduction so please add that.

2024-09-01 17:54 UTC, VincentLanglet commented
> Hey, I specifically asked for ConstantArrayTypeBuilderTest reproduction so please add that.

Sorry for the misunderstanding, it should be better now (?)

2024-09-01 18:53 UTC, ondrejmirtes requested changes
Otherwise I couldn't find any problem with this edit 👍

2024-09-01 18:53 UTC, ondrejmirtes commented on tests/PHPStan/Type/Constant/ConstantArrayTypeBuilderTest.php
> +		$oneOrZero = TypeCombinator::union(
Please also write some counter-example test as well. Like when we're setting a union offset that does not exist yet, that will make the array be no longer a list. Thanks.

2024-09-02 17:25 UTC, merged

2024-09-02 17:25 UTC, ondrejmirtes commented
Thank you.