Update functionMap.php for SplFileInfo::getPathInfo return type
phpstan/phpstan-src pull request #3487
Opened 2024-09-26 10:19 UTC by DannyvdSluijs

SplFileInfo::getPathInfo can return null as per documentation https://www.php.net/manual/en/splfileinfo.getpathinfo.php

After trying to report the issue in the distribution repo I was sent here, see https://github.com/phpstan/phpstan/issues/new?assignees=&labels=&projects=&template=Function_signature_mismatch.md. So I hope this is the right place and the right changes. Feel free to ping me if anything else is needed.

This mismatch was discovered using the following [code snippet](https://phpstan.org/r/82ae7b7b-aa9a-4dbc-9f08-146614fd4570)
```php
<?php declare(strict_types = 1);

$file = tempnam(sys_get_temp_dir(), 'phpstan-');
$info = new \SplFileInfo($file);

echo $info->getPathInfo()?->getPathname();
```

2024-09-26 10:25 UTC, DannyvdSluijs commented
> You've opened the pull request against the latest branch 2.0.x. PHPStan 2.0 is not going to be released for months. If your code is relevant on 1.12.x and you want it to be released sooner, please rebase your pull request and change its target to 1.12.x.

Rebased to `1.12.x`

2024-09-26 15:40 UTC, ondrejmirtes requested changes
I'd rather be a little bit calmer if it was a benevolent union type, so that it doesn't bother people who are sure it cannot fail for them.

2024-09-26 15:40 UTC, ondrejmirtes commented on resources/functionMap.php
> +'SplFileInfo::getPathInfo' => ['SplFileInfo|null', 'class_name='=>'string'],
```suggestion
'SplFileInfo::getPathInfo' => ['__benevolent<SplFileInfo|null>', 'class_name='=>'string'],
```

2024-10-06 14:28 UTC, merged

2024-10-06 14:28 UTC, ondrejmirtes commented
Thank you.