Add stub for openssl_sign() function
phpstan/phpstan-src pull request #3532
Opened 2024-10-03 11:43 UTC by piotrekkr

Adding openssl_sign() stub so PHPStan will correctly deduce `$signature` variable type which is now shown as `mixed` instead of `string`. 

Fixes #11791

2024-10-03 11:46 UTC, piotrekkr commented
Will rebase properly in a minute

2024-10-03 12:02 UTC, ondrejmirtes requested changes
You have to register this stub file in config/config.neon.

2024-10-03 12:33 UTC, piotrekkr commented
@ondrejmirtes Added it to conf/config.neon

2024-10-03 12:57 UTC, piotrekkr commented
Do I need to type all arguments or just this `@param-out` and the rest will be taken from signature? Asking because tests fail https://github.com/phpstan/phpstan-src/actions/runs/11162040542/job/31025901918 and they mention `$private_key` which is typed in function but seems like it is not enough.

2024-10-04 08:20 UTC, ondrejmirtes requested changes
Please fix proc_open() from https://github.com/phpstan/phpstan/issues/11777 too.

2024-10-04 08:20 UTC, ondrejmirtes commented
> Do I need to type all arguments

Copy the PHPdoc from jetbrains/phpstorm-stubs and leave out unimportant stuff like description.

2024-10-04 09:38 UTC, piotrekkr commented
@ondrejmirtes I've updated phpdoc. Let me know if I need to do something more. Thanks

2024-10-04 10:27 UTC, piotrekkr commented
@ondrejmirtes I think there is some bug in PHP manual of this `openssl_sign()` function. They mention about private key that can be one of those
```
#[\SensitiveParameter] OpenSSLAsymmetricKey|OpenSSLCertificate|array|string $private_key,
```
In description of input params, there is no mention of `array`, so my guess is that array is not allowed. I removed it from stub but not sure if it is good way to go. Lent me know what you think.

2024-10-04 10:32 UTC, piotrekkr commented
Made bug report for php docs https://github.com/php/doc-en/issues/3829

2024-10-04 10:58 UTC, piotrekkr commented
Also signature changed in PHP 8 so I should probably create two stub files right? Something like `openssl.stub` and `openssl_php8.stub`. Then do it similar to [this](https://github.com/phpstan/phpstan-src/blob/8f55339fa525386da6e4182156d342951e14b990/src/PhpDoc/SocketSelectStubFilesExtension.php#L17) to have both new and older php handled. Is it correct?

2024-10-07 08:34 UTC, piotrekkr commented
Okay [asked about this `array` in `private_key`](https://github.com/php/php-src/issues/16275) and it seems it is correct but docs are not updated properly so will need to wait for it to be updated and will then update this PR

2025-08-11 07:36 UTC, piotrekkr commented
I'll close this since there is no progress here.

2025-08-11 07:36 UTC, closed without merging