More precise md5/sha1 return type
phpstan/phpstan-src pull request #3541
Opened 2024-10-06 18:09 UTC by staabm

utilizing lowercase-string for this old school hashing functions

//cc @VincentLanglet

2024-10-06 19:07 UTC, VincentLanglet commented
If I understand correctly

You are using numeric-string in case only numbers are used ?
But numbers like 1234 is considered as a numeric string lowercased. (Only things like 10E2 are not but I dont think there is uppercase letter in sha or md5)

So it's non-falsy&numeric&lowercase|non-falsy&lowercase
Which can be simplified to non-falsy&lowercase.

I dont think there is a benefit to specify that sometimes it's a fully numeric string

2024-10-06 19:30 UTC, staabm commented
great feedback. I like the simplified version a lot more.

I am not yet used to thinking about numbers to be lowercase strings ;)

2024-10-08 08:46 UTC, ondrejmirtes requested changes

2024-10-08 08:46 UTC, ondrejmirtes commented on resources/functionMap.php
> +'md5' => ['(non-falsy-string&lowercase-string)', 'str'=>'string', 'raw_output='=>'bool'],
No need for the parentheses here.

2024-10-08 13:54 UTC, VincentLanglet approved these changes

2024-10-08 15:46 UTC, merged

2024-10-08 15:46 UTC, ondrejmirtes commented
Thank you!

2024-11-24 11:39 UTC, VincentLanglet commented
@staabm I'm not familiar with sha256 ; should the return type be updated too ?

2024-11-24 11:44 UTC, staabm commented
I am not familiar either. 

Tested a few inputs on https://emn178.github.io/online-tools/sha256.html and it seems you are right

2024-11-24 13:39 UTC, VincentLanglet commented
> I am not familiar either.
> 
> Tested a few inputs on [emn178.github.io/online-tools/sha256.html](https://emn178.github.io/online-tools/sha256.html) and it seems you are right

I'll do the PR as soon as I have confirmation this function really exists (cf my interrogation https://github.com/phpstan/phpstan/issues/12048#issuecomment-2496156102)