More precise `array_keys` return type
phpstan/phpstan-src pull request #3590
Opened 2024-10-28 17:28 UTC by staabm

closes https://github.com/phpstan/phpstan/issues/11928

2024-10-28 17:30 UTC, staabm commented on src/Type/Php/ArrayKeysFunctionDynamicReturnTypeExtension.php
> +		}
we could make this more sophisticated and support more filtering on constant array, but I think this is good enough for now.

until a few days ago I didn't even know `array_keys` can filter by values - it feels pretty rare

2024-10-29 05:47 UTC, herndlm commented
Just wondering if any of this could also be done inside `Type::getKeysArray()` as well? to e.g. avoid having to deal with lists outside of it again

2024-10-29 14:33 UTC, herndlm commented
Nice, sorry, noticed too late and should have mentioned it earlier. Later on, e.g. in https://github.com/phpstan/phpstan-src/pull/3514 I used `TrinaryLogic` instead of `bool` in the new Type function. Do you think you can use that too? 😊

2024-10-29 14:36 UTC, staabm commented
I used $strict as bool, because other methods in Type also use it. 

Do you see a use-case where Trinary would come in handy?

2024-10-29 16:54 UTC, herndlm commented
Not necessarily. If others use that too, then consistency makes sense IMO.

2025-01-19 13:36 UTC, ondrejmirtes requested changes

2025-01-19 13:36 UTC, ondrejmirtes commented on src/Type/Type.php
> +	public function getKeysArray(?Type $filterValueType = null, bool $strict = false): Type;
1) This a BC break
2) I don't like optional parameters at all.

The solution is to add another method that you'll use in the places where you're passing in the parameters now.

2025-01-19 15:24 UTC, staabm commented on tests/PHPStan/Analyser/nsrt/bug-11928.php
> +namespace Bug11928;
see https://phpstan.org/r/9a33d7fd-a8de-4eda-b4b5-0356e75da5a2

2025-03-10 14:39 UTC, herndlm commented on src/Type/Php/ArrayKeysFunctionDynamicReturnTypeExtension.php
> +		}
I think the diff makes sense, but don't get me wrong, just curious, currently this PR does effectively not change much of the behaviour, right? at least it does not use the new filter or strict arg, or am I missing something? It could be added in a follow-up, sure, but if that's also not the plan, than this only adds some list type to the result, or am I wrong?

2025-03-10 14:56 UTC, staabm commented on src/Type/Type.php
> +	public function getKeysArray(?Type $filterValueType = null, bool $strict = false): Type;
fixed

2025-07-17 13:23 UTC, ondrejmirtes commented
Please fix the conflict.

2025-07-17 14:12 UTC, staabm commented
resolved. build errors are unrelated and fixed separately in https://github.com/phpstan/phpstan-src/pull/4104

2025-07-17 14:52 UTC, merged

2025-07-17 14:52 UTC, ondrejmirtes commented
Thank you!