Improve `getopt()` function stub
phpstan/phpstan-src pull request #3655
Opened 2024-11-22 14:16 UTC by janedbal

Closes #12103

2024-11-22 14:17 UTC, janedbal commented on stubs/core.stub
> +function getopt(string $short_options, array $long_options = [], int &$rest_index = null): array|false {}
Should I delete the entry from functionMap?

2025-01-15 09:20 UTC, ondrejmirtes requested changes

2025-01-15 09:20 UTC, ondrejmirtes commented on stubs/core.stub
> + * @param-out int $rest_index
Can it be positive-int? Or maybe `int<0, max>`?

2025-03-04 12:51 UTC, janedbal commented on stubs/core.stub
> + * @param-out int $rest_index
Tested

```php
#!/usr/bin/env php
<?php

getopt('', [], $rest);

var_dump($rest);
```

both via `php foo.php` and `./foo.php`, always giving `int(1)`, so I used `positive-int`.

2025-04-15 12:21 UTC, merged

2025-04-15 12:22 UTC, ondrejmirtes commented
Thank you.