Explicit never early terminates
phpstan/phpstan-src pull request #366
Opened 2020-11-02 09:46 UTC by b1rdex

Closes https://github.com/phpstan/phpstan/issues/2638

2020-11-02 13:07 UTC, ondrejmirtes requested changes
This is almost perfect PR :) Please test it in a more modern way - see `NodeScopeResolverTest::testFileAsserts` - add a new dataProvider in it. You can use `assertVariableCertainty` function inside the test file. Thanks.

2020-11-03 02:58 UTC, b1rdex commented
@ondrejmirtes I updated the test

2020-11-03 07:41 UTC, ondrejmirtes requested changes

2020-11-03 07:41 UTC, ondrejmirtes commented on tests/PHPStan/Analyser/NodeScopeResolverTest.php
> +	public function phpDocNeverEarlyTerminates(): array
Needs to start with `data` as any other data provider here.

2020-11-03 07:41 UTC, ondrejmirtes commented on tests/PHPStan/Analyser/data/early-termination-phpdoc.php
> +	assertVariableCertainty(TrinaryLogic::createYes(), $pre);
I'm not even sure if these are executed. They might not be. Have you seen them fail?

The typical test here should be this instead:

```php
if (rand(0, 1)) {
    $a = 1;
} else {
    Foo::doBarPhpDoc();
}

assertVariableCertainty(TrinaryLogic::createYes(), $a);
```

2020-11-04 07:46 UTC, ondrejmirtes commented
Yeah, I just verified that the asserts are not verified because they're "dead code". I'll bring it over the finish line myselfů

2020-11-04 07:49 UTC, merged

2020-11-04 07:49 UTC, ondrejmirtes commented
Thank you. There needs to be a second part - verifying that a function with `@return never` actually never returns.