Enabling constructor check for class-string variables
phpstan/phpstan-src pull request #3661
Opened 2024-11-24 04:28 UTC by sayuprc

Changed to check constructor arguments when creating an instance from a variable containing a class-string.

resolve phpstan/phpstan#12010

2024-12-01 07:43 UTC, staabm commented on src/Rules/Classes/InstantiationRule.php
> +		if (str_starts_with($type->describe(VerbosityLevel::precise()), 'class-string')) {
could this use `Type->isClassStringType()`?

2024-12-01 07:45 UTC, staabm commented on src/Rules/Classes/InstantiationRule.php
> +			);
could this be shortened with `Type->getObjectClassReflections()`?

2024-12-02 13:18 UTC, sayuprc commented
@staabm 
Thank you for your reviewing!
I tried fixing with [298e55e](https://github.com/phpstan/phpstan-src/pull/3661/commits/298e55e79123c44068a009c11c8b89a042b89007)

2024-12-09 11:22 UTC, staabm approved these changes
lgtm thanks. 

please give ondej some time to work thru the queue of open PRs

2025-01-16 14:40 UTC, ondrejmirtes requested changes

2025-01-16 14:40 UTC, ondrejmirtes commented on src/Rules/Classes/InstantiationRule.php
> +		if (str_starts_with($type->describe(VerbosityLevel::precise()), 'class-string')) {
I'm sorry, rule logic can't rely on string type descriptions.

2025-01-16 14:40 UTC, ondrejmirtes commented on src/Rules/Classes/InstantiationRule.php
> +			if (0 < count($concretes)) {
```suggestion
			if (count($concretes) > 0) {
```

2025-01-16 14:45 UTC, merged

2025-01-16 14:45 UTC, ondrejmirtes commented
Thank you!