Named argument detection is scope php-version dependent
phpstan/phpstan-src pull request #3662
Opened 2024-11-24 09:09 UTC by staabm

2024-11-25 16:32 UTC, ondrejmirtes requested changes

2024-11-25 16:32 UTC, ondrejmirtes commented on tests/PHPStan/Rules/Functions/data/named-arguments.php
> +if (PHP_VERSION_ID < 80000) return;
We don't need this here, right? The test should run only on PHP 8+.

2024-11-25 16:45 UTC, staabm commented on tests/PHPStan/Rules/Functions/data/named-arguments.php
> +if (PHP_VERSION_ID < 80000) return;
the test which uses this file, has error expectations for PHP 7, see

https://github.com/phpstan/phpstan-src/blob/a0e007aee46a0a3ac56d74789f1107a87d0f5740/tests/PHPStan/Rules/Functions/CallToFunctionParametersRuleTest.php#L494-L499

2024-11-25 16:50 UTC, ondrejmirtes commented on tests/PHPStan/Rules/Functions/data/named-arguments.php
> +if (PHP_VERSION_ID < 80000) return;
It doesn't make sense to me. PHP 7.x does not support named arguments so it doesn't make sense to check them?

2024-11-25 17:37 UTC, staabm commented on tests/PHPStan/Rules/Functions/data/named-arguments.php
> +if (PHP_VERSION_ID < 80000) return;
so do you say I should skip the test on php7, or should the test be made to assert 0 errors on php7?

2024-11-26 07:57 UTC, staabm commented on tests/PHPStan/Rules/Functions/data/named-arguments.php
> +if (PHP_VERSION_ID < 80000) return;
I went with skipping the tests for now

2024-12-20 09:04 UTC, merged

2024-12-20 09:04 UTC, ondrejmirtes commented
Thank you.