Implement SocketCreateReturnTypeExtension
phpstan/phpstan-src pull request #3667
Opened 2024-11-25 13:06 UTC by staabm

2024-11-26 13:44 UTC, ondrejmirtes requested changes

2024-11-26 13:44 UTC, ondrejmirtes commented on src/Php/PhpVersions.php
> +		return IntegerRangeType::fromInterval(null, 79999)->isSuperTypeOf($this->phpVersions)->result;
I'd write this as "since 8.0" rather than until "7.9999". So rename this method to what it actually returns since 8.0.

2024-11-26 13:53 UTC, staabm commented on src/Php/PhpVersions.php
> +		return IntegerRangeType::fromInterval(null, 79999)->isSuperTypeOf($this->phpVersions)->result;
sure

2024-11-26 13:59 UTC, staabm commented
broken build is unrelated

2024-11-26 18:44 UTC, staabm commented
just found https://php.watch/versions/8.0/sockets-sockets-addressinfo which describes all functions which have been changed from `resource` to `Socket`-objects. 
I have double checked the php.net manual for all of them and it turned out they have the same parameter signature so we can re-use the extension for all of them.

2025-01-16 15:25 UTC, ondrejmirtes commented
I'm hesitant to merge this. If PHPStan were to properly merge reflection data across multiple supported PHP versions then this PR wouldn't be needed at all. It's really weird to implement this for a single function when the rest of PHPStan doesn't really support this.

2025-01-16 16:02 UTC, thg2k commented
> I'm hesitant to merge this. If PHPStan were to properly merge reflection data across multiple supported PHP versions then this PR wouldn't be needed at all. It's really weird to implement this for a single function when the rest of PHPStan doesn't really support this.

I agree. I think PHPStan should have its own meta-type that automatically resolves to the correct type (i.e. resource/object) according to the current php version.

At the moment i'm happily using this hack: https://github.com/phpstan/phpstan/discussions/4212#discussioncomment-284814

The problem is that it works only within the same project, i.e. as the phpstan.neon file is local to the project it does not "export" easily, so for methods facing externally I have to type it as "mixed".

These are the type aliases i'm currently using:

```
	typeAliases: (php 7.x)
		resource_gd: 'resource'
		resource_gdfont: 'int'
		resource_socket: 'resource'

	typeAliases: (php 8.x)
		resource_gd: '\GdImage'
		resource_gdfont: '\GdFont'
		resource_socket: '\Socket'

```

Also note that some types have been introduced in different versions, so for example GdImage and Socket are 8.0 while GdFont is 8.1

2025-01-18 08:36 UTC, closed without merging