Assert-and-throws-are-side-effects
phpstan/phpstan-src pull request #3719
Opened 2024-12-10 03:57 UTC by jack-worman

Closes https://github.com/phpstan/phpstan/issues/12224

2025-01-16 15:10 UTC, ondrejmirtes requested changes

2025-01-16 15:10 UTC, ondrejmirtes commented on tests/PHPStan/Rules/Pure/PureFunctionRuleTest.php
> +			['Function PHPStan\Rules\Pure\data\pureWithThrowsVoid() is marked as pure but returns void.', 18],
```suggestion
			[
				'Function PHPStan\Rules\Pure\data\pureWithThrowsVoid() is marked as pure but returns void.',
				18,
			],
```

2025-01-16 15:10 UTC, ondrejmirtes commented on tests/PHPStan/Rules/Pure/PureMethodRuleTest.php
> +		$this->analyse([__DIR__ . '/data/bug-12224.php'], [
I don't get it, why did you delete this test? You should only add a new test.

2025-03-23 17:23 UTC, jack-worman commented on tests/PHPStan/Rules/Pure/PureMethodRuleTest.php
> +		$this->analyse([__DIR__ . '/data/bug-12224.php'], [
not sure why i did that. Reverted the delete

2025-05-05 16:09 UTC, merged

2025-05-05 16:09 UTC, ondrejmirtes commented
Thank you!