Fix crash on MethodCallableNode on do while
phpstan/phpstan-src pull request #3752
Opened 2024-12-22 15:23 UTC by samsonasik

Fixes https://github.com/phpstan/phpstan/issues/12246

Ref https://phpstan.org/r/178ac73a-e99c-4961-957f-a3c6062d7c44
Ref https://3v4l.org/5s30L

2024-12-22 15:27 UTC, samsonasik commented
Ready to merge 👍

2024-12-23 16:34 UTC, ondrejmirtes requested changes
1) MethodCallableNode is not the only one with this problem. There's also FunctionCallableNode, InstantiationCallableNode, StaticMethodCallableNode. Please reproduce and fix issues with them too.
2) Crashing examples have regression tests in AnalyserIntegrationTest, not in a specific rule. Because we're not fixing an error in a specific rule.
3) Printing of custom nodes is fixed by adding a method on PHPStan\Node\Printer\Printer, not by modifying ExprPrinter.

Thanks.

2024-12-24 02:34 UTC, samsonasik commented
I will try

2026-04-25 22:05 UTC, VincentLanglet commented
https://github.com/phpstan/phpstan/issues/12246 is now closed so I think we can close this.

2026-04-25 22:05 UTC, closed without merging