Improve `preg_split()` function ReturnType
phpstan/phpstan-src pull request #3757
Opened 2024-12-26 07:34 UTC by malsuke

I developed further extended the extension for the `preg_split()` function.

The `preg_split()` function can specify ReturnType with the following cases:

- When the regular expression passed as the `$pattern` argument is invalid.
- When the `$pattern` and `$subject` arguments are constants.
- When the string passed as the `$subject` argument is non-empty-string.
- When the `$flag` argument is set to one or more of the following: `PREG_SPLIT_OFFSET_CAPTURE`, `PREG_SPLIT_NO_EMPTY`, or `PREG_SPLIT_DELIM_CAPTURE`.

The detailed cases are specified in the test cases.

Additionally, the current default return type is set to `list<string>|false`. However, depending on the flags, it also return `list<array{string, int<0, max>}>`. To account for this, I have added support for this possibility and applied a benevolent union to cover all three types. So, I set `__benevolent<list<string>|list<array{string, int<0, max>}>|false>` to the basic return type.

2024-12-26 09:41 UTC, zonuexe commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +		}
By replacing it as follows, type checking within multiple Constant loops will no longer be necessary.

```php
$flags = [];
$flagType = $scope->getType($flagArg->value);
foreach ($flagType->getConstantScalarValues() as $flag) {
    if (!is_int()) {
        return new ErrorType();
    }

    $flags[] = $flag;
}
```

2024-12-26 10:00 UTC, zonuexe commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +		}
resolved https://github.com/phpstan/phpstan-src/pull/3757/commits/8cb3030cbe2e0cbf4da1d42bb9198d450d136df9

2025-01-05 11:59 UTC, VincentLanglet commented on resources/functionMap.php
> +'preg_split' => ['__benevolent<list<string>|list<array{string, int<0, max>}>|false>', 'pattern'=>'string', 'subject'=>'string', 'limit='=>'?int', 'flags='=>'int'],
The other preg_ method are not using benevolent union, so I would think more consistent to not use a benevolent union here too.

2025-01-14 00:39 UTC, malsuke commented on resources/functionMap.php
> +'preg_split' => ['__benevolent<list<string>|list<array{string, int<0, max>}>|false>', 'pattern'=>'string', 'subject'=>'string', 'limit='=>'?int', 'flags='=>'int'],
fix 37f9b3e2650da6d6bd16323d8a1609a3eb5caad6

2025-01-14 02:36 UTC, malsuke commented on resources/functionMap.php
> +'preg_split' => ['__benevolent<list<string>|list<array{string, int<0, max>}>|false>', 'pattern'=>'string', 'subject'=>'string', 'limit='=>'?int', 'flags='=>'int'],
@VincentLanglet @ondrejmirtes 

I understand. I would like to remove benevolent union.

On the other hand, I think that preg_split should not return false unless there is an issue with the regular expression. Furthermore, in this PR, I have modified the code so that if the regular expression is incorrect, an error is returned early in the parsing process.

Therefore, if the regular expression is correct, I am considering not adding false as a Union.
(In this case, this bug can also be fixed. https://github.com/phpstan/phpstan-src/blob/76740fd95bbe616331c66de45f489c697163a52b/tests/PHPStan/Analyser/AnalyserIntegrationTest.php#L890-L900)

If you think not to use benevolent union, do you think it would be fine to remove false? I would like to hear your opinion on this. I would like to get your opinion before making any modifications.

2025-01-14 07:17 UTC, VincentLanglet commented on resources/functionMap.php
> +'preg_split' => ['__benevolent<list<string>|list<array{string, int<0, max>}>|false>', 'pattern'=>'string', 'subject'=>'string', 'limit='=>'?int', 'flags='=>'int'],
Like any other preg method I think it can returns false if an internal error occurs like
- some memory limit is reached
- too many recursion
- some invalid encoding

And in the pho.ini there is some config like pcre.recursion_limit or pcre.backtrack_limit.

So I would keep a non-benevolent union AND false.

If we decide to remove false from the signature it should be removed from all the preg methods. But I dont think we should go this way.

2025-01-14 07:53 UTC, malsuke commented on resources/functionMap.php
> +'preg_split' => ['__benevolent<list<string>|list<array{string, int<0, max>}>|false>', 'pattern'=>'string', 'subject'=>'string', 'limit='=>'?int', 'flags='=>'int'],
I understand.
I modified it to keep a non-benevolent union AND false.

37f9b3e2650da6d6bd16323d8a1609a3eb5caad6

2025-03-01 15:20 UTC, ondrejmirtes commented
@staabm As this is about regexes, can you please review it? Thank you.

2025-03-02 09:37 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +			&& @preg_match($patternConstantTypes[0]->getValue(), '') === false
we usually us `Strings::match`

2025-03-02 09:37 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +		$subjectConstantTypes = $subjectType->getConstantStrings();
I would move the subject type declartion below the early returning if in the next block

2025-03-02 09:37 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +					return new ErrorType();
this case is missing a test

2025-03-02 09:37 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +					return new ErrorType();
this case is missing a test

2025-03-02 09:37 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +						$result = @preg_split($patternConstantType->getValue(), $subjectConstantType->getValue(), $limit, $flag);
use `Strings::split`

2025-03-02 09:37 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +				if (!is_int($limit)) {
numeric-string $limit is not an error

https://3v4l.org/JuFHj

2025-03-02 09:37 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +			&& @preg_match($patternConstantTypes[0]->getValue(), '') === false
this needs to check all patterns

https://3v4l.org/495b1

2025-03-02 09:37 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +				if (!is_int($flag)) {
to be consistent with limit, this might also allow numeric-string

https://3v4l.org/PqFaA

2025-03-02 09:37 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +		return TypeCombinator::union(...$resultTypes);
I think we are missing `false`. in the `preg_match` inference we decided this can get false even if all args a valid and static analysis time known, because a regex pattern might be super inefficient (or pattern based attacks might trick the regex engine into return false)

2025-03-02 09:37 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +		if (count($patternConstantTypes) === 0 || count($subjectConstantTypes) === 0) {
this if-branch might be factored out into a private method for readability

2025-03-02 09:39 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +							continue;
if one of the static analysis time values make `preg_split` return `false` we should give-up instead of ignoring this fact

2025-03-07 04:57 UTC, malsuke commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +						$result = @preg_split($patternConstantType->getValue(), $subjectConstantType->getValue(), $limit, $flag);
I think using Strings::split here is not right because the limit is fixed to -1.

2025-03-07 05:23 UTC, malsuke commented
@staabm 
Thanks for your review.
I've made revisions based on the feedback. Please review again.

2025-03-08 08:18 UTC, staabm requested changes
> So, I set __benevolent<list<string>|list<array{string, int<0, max>}>|false> to the basic return type.

it seems this is no longer true

2025-03-08 08:18 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +			if (!$limitType->isInteger()->yes() && !$limitType->isString()->yes()) {
I think this won't work for a limit like `5|'17'`. could work with `->toInteger()` beforehand.

same for $flag

please add tests for this cases

2025-03-08 08:18 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +				$flagState = $this->bitwiseFlagAnalyser->bitwiseOrContainsConstant($flagArg->value, $scope, 'PREG_SPLIT_OFFSET_CAPTURE');
```suggestion
				$capturesOffset = $this->bitwiseFlagAnalyser->bitwiseOrContainsConstant($flagArg->value, $scope, 'PREG_SPLIT_OFFSET_CAPTURE');
```

2025-03-08 08:18 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +			if ($returnNonEmptyStrings) {
I would inline this only once used variable to ease reading the code

2025-03-08 08:18 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +		return TypeCombinator::union(...$resultTypes);
I think the above comment is still true and we are missing the `false` here

2025-03-11 02:47 UTC, malsuke commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +		return TypeCombinator::union(...$resultTypes);
So, does this mean that every possible result of preg_split includes the possibility of false, and therefore we need to add false to the union type? 

I had implemented it to return an Error if preg_split returns false, as a warning.   
So, does this mean I should include false in all cases, instead of returning Error?

2025-03-11 02:47 UTC, malsuke commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +			if (!$limitType->isInteger()->yes() && !$limitType->isString()->yes()) {
I realized that using toInteger() beforehand wasn't ideal because it would convert array and null inputs into int(0), which is incorrect.  So, I added a check using isConstantScalarValue() to ensure we can accurately handle values like 5|'14'.

2025-03-11 06:16 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +		return TypeCombinator::union(...$resultTypes);
The return type of `false` is necessary because the `preg_split` call can fail even if we know everything. 

The current "return ErrorType" could be turned into "return null" in case other rules will already report a phpstan error.

2025-03-12 12:49 UTC, malsuke commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +		return TypeCombinator::union(...$resultTypes);
I have fixed about that in the following commit.
307cf54ac64f11d2f7c8b95a7ada046782aa912f

Additionally, since handling for the false case is no longer necessary, I have removed `if ($result === false)`.

2025-04-17 04:54 UTC, yuk1-ishida commented
Sorry for the delay since the last commit. Could you please review it again?
@VincentLanglet @ondrejmirtes

2025-04-17 04:55 UTC, malsuke commented
Sorry for the delay since the last commit. Could you please review it again?
@VincentLanglet @ondrejmirtes

2025-05-13 14:10 UTC, ondrejmirtes requested changes
Other than this I'm waiting for a final LGTM from @staabm  😊

2025-05-13 14:10 UTC, ondrejmirtes commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +		return $type->isInteger()->yes() || $type->isString()->yes() || $type->isConstantScalarValue()->yes();
This logic will fail for `int|string`. The proper way to ask this is `(new UnionType([new IntegerType(), new StringType()]))->isSuperTypeOf($type)`. Also remove the `isConstantScalarValue` part (there non-int/non-string scalars as well).

2025-05-13 14:11 UTC, ondrejmirtes requested changes

2025-05-13 14:11 UTC, ondrejmirtes commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +				[new ConstantIntegerType(0), new ConstantIntegerType(1)],
Please use ConstantArrayTypeBuilder instead of new ConstantArrayType.

2025-05-13 15:19 UTC, staabm commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +		if ($limitArg === null) {
similar to https://github.com/phpstan/phpstan-src/pull/3970/files we should not only handle a absent argument, but also a explicit `null` passed:

e.g. `preg_split($pattern, $subject, null, PREG_SPLIT_NO_EMPTY);`

2025-05-13 15:25 UTC, staabm approved these changes

2025-05-15 03:07 UTC, yuk1-ishida commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +		return $type->isInteger()->yes() || $type->isString()->yes() || $type->isConstantScalarValue()->yes();
fixed 1ee1a792c4d4d681d74e52724e9ccd907f02116b

2025-05-15 03:07 UTC, yuk1-ishida commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +				[new ConstantIntegerType(0), new ConstantIntegerType(1)],
fixed 1ee1a792c4d4d681d74e52724e9ccd907f02116b

2025-05-15 03:08 UTC, malsuke commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +		return $type->isInteger()->yes() || $type->isString()->yes() || $type->isConstantScalarValue()->yes();
fixed: 1ee1a792c4d4d681d74e52724e9ccd907f02116b

2025-05-15 03:08 UTC, malsuke commented on src/Type/Php/PregSplitDynamicReturnTypeExtension.php
> +				[new ConstantIntegerType(0), new ConstantIntegerType(1)],
fixed: 1ee1a792c4d4d681d74e52724e9ccd907f02116b

2025-05-16 09:32 UTC, merged

2025-05-16 09:32 UTC, ondrejmirtes commented
Thank you!