Use ReturnTypeExtension for mb_str_split
phpstan/phpstan-src pull request #379
Opened 2020-11-23 11:26 UTC by VincentLanglet

Shouldn't `mb_str_split` works as `str_split` ?

2020-11-23 12:12 UTC, ondrejmirtes requested changes
And a test. See where str_split is already tested.

2020-11-23 12:12 UTC, ondrejmirtes commented on src/Type/Php/StrSplitFunctionReturnTypeExtension.php
> +			|| $functionReflection->getName() === 'mb_str_split';
Use in_array please.

2020-11-25 22:22 UTC, VincentLanglet commented
@ondrejmirtes The PR seems fine to me now. But all the test are failing weirdly.

2020-11-26 11:02 UTC, merged

2020-11-26 11:02 UTC, ondrejmirtes commented
Thank you!

2020-11-26 11:03 UTC, ondrejmirtes commented
I fixed the CI with: https://github.com/phpstan/phpstan-src/commit/ef6ca4abbc4db0a2f1ce2a2bdb45bd8ce8235378

Something weird is going on with latest version of nette/di...

2020-11-29 12:41 UTC, VincentLanglet commented
> Thank you!

Thanks you too. 
I look forward the next release to fix all the false-positive I got when I change `str_plit` into `mb_str_split`.