Support `@psalm-pure` and `@phpstan-pure` annotations
phpstan/phpstan-src pull request #412
Opened 2020-12-25 06:42 UTC by b1rdex

1. `CallToFunctionStamentWithoutSideEffectsRuleTest` doesn't find errors and I don't know how to fix it. Running analysis with `bin/phpstan` finds them correctly.
2. This needs more rules to check the bodies of `@pure` functions/methods for purity. I think this might be postponed for now and solved in the future.

2020-12-27 10:53 UTC, ondrejmirtes requested changes
Thank you, I appreciate this. Although there's much more work that needs to be done, I don't want to be exactly 1:1 with Psalm as this area is very complicated. I consider "pure" functions to consist of two attributes - hasSideEffects, and isDeterministic. We can find examples of functions and methods in all 4 brackets - yes/yes, yes/no, no/yes, no/no. And they behave differently and different situations, which will influence the analysis.

2020-12-27 10:53 UTC, ondrejmirtes commented on src/PhpDoc/PhpDocNodeResolver.php
> +			if (in_array($phpDocTagNode->name, ['@psalm-pure', '@phpstan-pure'], true)) {
@pure without prefix should also be supported.

2020-12-27 10:53 UTC, ondrejmirtes commented on tests/PHPStan/Rules/Methods/data/static-method-call-statement-no-side-effects-phpdoc.php
> +BzzStatic::pure2('test');
This should be put into an anonymous function so that it's not called with runtime reflection.

2020-12-27 10:53 UTC, ondrejmirtes commented on tests/PHPStan/Rules/Methods/data/method-call-statement-no-side-effects-phpdoc.php
> +(new Bzz())->regular('test');
This should be put into an anonymous function so that it's not called with runtime reflection.

2020-12-27 10:53 UTC, ondrejmirtes commented on tests/PHPStan/Rules/Functions/data/function-call-statement-no-side-effects-phpdoc.php
> +function pure2(string $a): string {return $a;}
This file should be separated into two files - one with function definitions, one with their calls.

2020-12-28 08:41 UTC, b1rdex commented
@ondrejmirtes done

2021-01-11 08:52 UTC, ondrejmirtes commented
Added a commit with backwards compatibility and also the ability to set "impure" functions: https://github.com/phpstan/phpstan-src/pull/412/commits/c99316d49549787a170fd2c1ff9c08fcc70c02ab

2021-01-11 09:30 UTC, merged

2021-01-11 09:30 UTC, ondrejmirtes commented
@b1rdex Thank you!