Corrected bcdiv and bcmul return types for PHP 8.
phpstan/phpstan-src pull request #546
Opened 2021-06-05 13:18 UTC by khkramer

2021-06-05 13:23 UTC, ondrejmirtes requested changes

2021-06-05 13:23 UTC, ondrejmirtes commented on tests/PHPStan/Analyser/NodeScopeResolverTest.php
> +			yield from $this->gatherAssertTypes(__DIR__ . '/data/bcmath-dynamic-return.php');
What happens on PHP 8 also needs to be tested.

2021-06-06 15:20 UTC, ondrejmirtes commented
Fixes https://github.com/phpstan/phpstan/issues/5134

2021-09-01 15:44 UTC, staabm commented
@khkramer any plans to finalize this PR?

2022-02-08 12:27 UTC, closed without merging

2022-02-17 04:36 UTC, dmitryuk commented
@ondrejmirtes Why PR was closed? The bug is still present