copy php configurations when fork child workers
phpstan/phpstan-src pull request #559
Opened 2021-06-21 07:04 UTC by yangchaobj

Currently, ProcessHelper only copy command-line arguments, but ignore those of php itself.
In some cases, the custom configuration for php: --configuration (-c in short), is very usefull.

for example:
If a custom php.ini is specified when starting phpstan like:
php74 -c my-php.ini analyze --level 0 ...

# my-php.ini
extension=yaf
yaf.use_namespace = On
...

phpstan creates child workers to analyze, however, it only copies its own the command-line arguments, not those of php itself (-c my-php.ini). 
In workers, "yaf.use_namespace" could not take effect, the reference to "Yaf\Application" will generate "Yaf\Application not found" error message.

2021-06-22 18:43 UTC, dktapps commented
I'd also find this useful, since PHPStan and JIT don't work so well together on Windows, and it's tiresome to have to disable it in php.ini.

2021-06-26 15:08 UTC, ondrejmirtes commented
> since PHPStan and JIT don't work so well together on Windows

Looks like you have a different root issue @dktapps that should be addressed.

2021-06-26 15:34 UTC, ondrejmirtes requested changes

2021-06-26 15:34 UTC, ondrejmirtes commented on src/Process/ProcessHelper.php
> +		$phpCmd = ($phpIni === false) ? escapeshellarg(PHP_BINARY) : sprintf('%s -c %s', escapeshellarg(PHP_BINARY), $phpIni);
`$phpIni` needs to be escaped as well

2021-06-26 15:37 UTC, dktapps commented
> > since PHPStan and JIT don't work so well together on Windows
> 
> Looks like you have a different root issue @dktapps that should be addressed.

I know, but I've been unsuccessful at identifying the root cause of the problem after several months of investigation. I know it has something to do with subprocesses, but I'm not sure exactly what - something leads to PHP segfaulting in PM analysis runs.

I end up disabling JIT as a workaround, but PHPStan makes that difficult due to not passing CLI arguments to subprocesses.

2021-06-26 16:24 UTC, yangchaobj commented on src/Process/ProcessHelper.php
> +		$phpCmd = ($phpIni === false) ? escapeshellarg(PHP_BINARY) : sprintf('%s -c %s', escapeshellarg(PHP_BINARY), $phpIni);
oh yes, you are right, let me fix it.

2021-06-26 16:58 UTC, merged

2021-06-26 16:58 UTC, ondrejmirtes commented
Thank you!