rework IntegerRange math impl
phpstan/phpstan-src pull request #653
Opened 2021-08-30 15:52 UTC by staabm

2021-08-30 19:22 UTC, staabm commented
@ondrejmirtes my local testing shows me that math.php tests are now passing. some of the initially-added integer-range-math tests in `integer-range-types.php` are failling though.

are you comfortable enough with the newly added failling tests, that I could/should drop those in `integer-range-types.php` - I feel these are mostly redundant with your new tests...

2021-08-30 20:43 UTC, ondrejmirtes commented
@staabm Please don't delete any tests :) If you want to adjust the asserts if you feel like the new ones make more sense then fine, but don't delete any asserts...

2021-08-31 11:06 UTC, staabm commented
@ondrejmirtes thx integer-range related tests I created with the first iteration of integer-math and the one you added pass now.

could you help me interpreting the remaining errors.. I am not sure whether these are related to my PR or how to fix them.

2021-08-31 11:19 UTC, ondrejmirtes requested changes

2021-08-31 11:19 UTC, ondrejmirtes commented on src/Analyser/MutatingScope.php
> +				$math = static function (IntegerRangeType $range, $node, $operand) use (&$math): Type {
Callback referencing itself like this leads to memory leak explosion. Please have a private method instead.

2021-08-31 11:32 UTC, staabm commented on src/File/ParentDirectoryRelativePathHelper.php
> +		if ($dotsCount < 0) {
I had to re-add these lines, which were deleted with https://github.com/phpstan/phpstan-src/pull/637/files#r696555714

it seems it was a false-positive that phpstan could detect this case with the new integer-range math

2021-08-31 11:32 UTC, staabm commented on tests/PHPStan/Analyser/data/integer-range-types.php
> +		assertType('float|int<0, 10>', $r1 / $z);
after I added coverage for the test-cases in https://github.com/phpstan/phpstan-src/pull/652 I realized that these operations here can be expressed more precily. and therefore we have the changes here

2021-08-31 11:32 UTC, staabm commented on tests/PHPStan/Analyser/data/integer-range-types.php
> +		assertType('int<min, 2>', 2 - $pi);
a bug in the previous expectations

2021-08-31 11:58 UTC, ondrejmirtes commented
I'm gonna look into the remaining failures.

2021-08-31 13:01 UTC, ondrejmirtes commented
Alright, this should be ready. Let's see what CI says 🤞

2021-08-31 13:02 UTC, ondrejmirtes commented
@staabm Please check the commits to see what I had to do.

2021-08-31 13:09 UTC, ondrejmirtes commented
I'm happy with this, thanks for the help!

2021-08-31 13:09 UTC, merged

2021-08-31 13:09 UTC, staabm commented
> I'm happy with this, thanks for the help!

thank you for getting it in shape to land it!

2021-08-31 13:11 UTC, staabm commented
>  Please check the commits to see what I had to do.

the commits itself logic logical to me. I was not able make sense of the test-errors and derive the necessary changes from it.

hopefully with more experience of the codebase this will get better over time.