Fix the return types of round()/ceil()/floor()
phpstan/phpstan-src pull request #729
Opened 2021-10-23 20:26 UTC by johnbillion

On PHP < 8 these functions return boolean false when the `$num` parameter is an array: https://3v4l.org/J9KkP

PHPStan correctly reports an error if the type of `$num` is known and not `int|float`, but it's possible for the type not to be known.

This playground example is as good as I could manage: https://phpstan.org/r/59f77cf2-a658-4f2b-9630-80c778714ab2

2021-11-04 10:22 UTC, johnbillion commented
I'm not sure what the failing tests are telling me. They seem unrelated to this change but I don't have a good enough understanding of PHPStan internals to know for sure. Guidance appreciated.

2022-01-31 22:04 UTC, ondrejmirtes commented
I'd love to use this, can you please rebase and make the build green? Thank you.

2022-02-01 19:35 UTC, ondrejmirtes commented
There's still a lot of failures.

2022-02-01 19:51 UTC, johnbillion commented
It's difficult to determine what's failing due to this change and what's also failing in master currently. I'll wait until master is green then take another look.

2022-02-01 19:53 UTC, ondrejmirtes commented
Yeah, you can safely rebase now :)

2022-02-02 11:06 UTC, ondrejmirtes requested changes

2022-02-02 11:06 UTC, ondrejmirtes commented on src/Type/Php/RoundFunctionReturnTypeExtension.php
> +		if (PHP_VERSION_ID >= 80000) {
You need to use `PhpVersion` injected to constructor, and call a specific method on it. Something like `hasStricterRoundFunctions()` or something like that.

2022-02-02 11:06 UTC, ondrejmirtes commented on src/Type/Php/RoundFunctionReturnTypeExtension.php
> +		if (PHP_VERSION_ID >= 80000) {
dtto

2022-02-03 11:32 UTC, ondrejmirtes approved these changes

2022-02-03 11:33 UTC, merged

2022-02-03 11:33 UTC, ondrejmirtes commented
Thank you!

2022-02-03 11:53 UTC, johnbillion commented
Thanks for helping get it over the finishing line :-)