Implement feature 5973 - add SARIF output format
phpstan/phpstan-src pull request #765
Opened 2021-11-12 14:51 UTC by llaville

As it is my first PR on this project, hope I don't forget any steps.

- `make cs` OK
- `make tests` OK

My first remark:

- As I don't found any API / constant that give current PHPStan version, I've hardcoded it in `SarifErrorFormatter` and unit tests.

Waiting for your feedbacks

2021-11-12 15:27 UTC, llaville commented
`make phpstan` has an error (even on master branch)

```
php bin/phpstan clear-result-cache -q && php -d memory_limit=768M bin/phpstan
Note: Using configuration file /shared/backups/github/my-phpstan-src/phpstan.neon.dist.
 1263/1263 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ----------------------------------------------------------------------------------------------------------
  Line   src/Rules/RuleErrorBuilder.php
 ------ ----------------------------------------------------------------------------------------------------------
         Ignored error pattern #^Variable property access on PHPStan\\Rules\\RuleError\.$# in path
         /shared/backups/github/my-phpstan-src/src/Rules/RuleErrorBuilder.php was not matched in reported errors.
  149    Variable property access on object.
  152    Method PHPStan\Rules\RuleErrorBuilder::build() should return PHPStan\Rules\RuleError but returns object.
 ------ ----------------------------------------------------------------------------------------------------------


 [ERROR] Found 3 errors


make: *** [Makefile:59: phpstan] Error 1
```

2022-02-01 12:20 UTC, ondrejmirtes requested changes
And please fix the Windows failures :)

2022-02-01 12:20 UTC, ondrejmirtes commented on conf/bleedingEdge.neon
> +		class: PHPStan\Command\ErrorFormatter\SarifErrorFormatter
This should be in `config.neon.`

2022-02-01 12:20 UTC, ondrejmirtes commented on composer.json
> +		"bartlett/sarif-php-sdk": "^1.0",
Please try to do this without a dependency. It's just encoding a simple JSON after all.

2022-02-01 12:20 UTC, ondrejmirtes commented on src/Command/ErrorFormatter/SarifErrorFormatter.php
> +		$driver->setVersion('1.1.2');
The version can be obtained like this: https://github.com/phpstan/phpstan-src/blob/1789915a3ed766e8e784ac3eabee4b327e9d192a/bin/phpstan#L109-L114

2022-05-15 19:06 UTC, ondrejmirtes commented
Feel free to open a new PR if you decide to finish this, thanks :)

2022-05-15 19:06 UTC, closed without merging