Detect deprecated methods from the interface as well.
phpstan/phpstan-src pull request #792
Opened 2021-11-20 12:10 UTC by eiriksm

Based on feedback from phpstan/phpstan-deprecation-rules#49

Initial bug report on that repo: phpstan/phpstan-deprecation-rules#48

2021-11-20 12:43 UTC, ondrejmirtes requested changes

2021-11-20 12:43 UTC, ondrejmirtes commented on tests/PHPStan/Reflection/Annotations/DeprecatedAnnotationsTest.php
> +		$this->assertTrue($class->getMethod('superDeprecated', $scope)->isDeprecated()->yes());
I don't like mocking, you can call `getNativeMethod` instead

2021-11-20 12:43 UTC, ondrejmirtes commented on tests/PHPStan/Reflection/Annotations/DeprecatedAnnotationsTest.php
> +		require_once __DIR__ . '/data/annotations-deprecated.php';
The require doesn't need to be there. You just need to make sure to run `composer dump` locally before running tests.

2021-11-20 22:16 UTC, ondrejmirtes commented
Can you please rebase and force push so that the history is linear with no merge commits? Thank you.

2021-11-21 04:32 UTC, eiriksm commented
Of course, no problem. Thanks for your time Ondrej, and thanks again for the family of phpstan libraries!

2021-11-21 06:54 UTC, merged

2021-11-21 06:54 UTC, ondrejmirtes commented
Thank you!

2022-02-17 14:23 UTC, ossinkine commented
@ondrejmirtes @eiriksm Actually this is wrong behavour and conflicts with https://github.com/phpstan/phpstan/issues/3378. The assumption that if a method in a parent class is deprecated, then a method in a child class should also be deprecated is not correct.

I have an example. [`Doctrine\ORM\Event\LifecycleEventArgs`](https://github.com/doctrine/orm/blob/152c04c03d68d39f485d367713dd69dec0f4106d/lib/Doctrine/ORM/Event/LifecycleEventArgs.php) extends [`Doctrine\Persistence\Event\LifecycleEventArgs`](https://github.com/doctrine/persistence/blob/0130920efd696cf5480744f499672b2d4ca47c85/lib/Doctrine/Persistence/Event/LifecycleEventArgs.php). Parent class has deprecated `getEntity` method and child class contain it but in child class it is not deprecated and should not be so.

So I suggest to revert this changes.