make mysqli_result generic
phpstan/phpstan-src pull request #896
Opened 2021-12-29 15:06 UTC by staabm

2021-12-29 15:43 UTC, ondrejmirtes requested changes

2021-12-29 15:43 UTC, ondrejmirtes commented on conf/config.neon
> +			'mysqli'
You're making `mysqli_result` generic, not `mysqli`

2021-12-29 15:52 UTC, staabm commented on stubs/mysqli.stub
> + * @template TValue
```suggestion
 * @template TValue of object
```

2022-01-02 10:12 UTC, ondrejmirtes commented
Can you please also test various `mysqli_fetch_object` calls? The situation is quite complex so I'd like to verify the generic function works. Thank you.

2022-01-03 16:19 UTC, staabm commented
added a few positive tests. do you have something more in mind, when you say "various" ? :-)

2022-01-21 09:48 UTC, staabm commented
since I have put these stubs in phpstan-dba, I will close this PR.

having them inside the database related repo gives me more flexibility and I think is the best thing long term, as phpstan-src needs to stay more generic and cannot per default be as opinionated as phpstan-dba might needs to be

2022-01-21 09:48 UTC, closed without merging