version_compare() operator can be null
phpstan/phpstan-src pull request #967
Opened 2022-01-31 19:40 UTC by staabm

closes https://github.com/phpstan/phpstan/issues/4457

2022-01-31 19:42 UTC, staabm commented on src/Type/Php/VersionCompareFunctionDynamicReturnTypeExtension.php
> +	private $operators = [
all operators as defined in https://www.php.net/manual/en/function.version-compare.php

2022-02-01 08:56 UTC, staabm commented
the positive cases are already covered in https://github.com/phpstan/phpstan-src/blob/fcfe9b9851fc640859aa02cebcfbfb84ee51624c/tests/PHPStan/Analyser/data/functions.php#L15-L22

2022-02-01 09:05 UTC, clxmstaab commented
the remaining error is unrelated/fixed on master. should I rebase or do you just merge it as is?

2022-02-01 09:08 UTC, ondrejmirtes requested changes

2022-02-01 09:08 UTC, ondrejmirtes commented on tests/PHPStan/Analyser/data/bug-4457-php7.php
> +		$result = version_compare($version1, $version2, $comparator);
This regression test doesn't test anything here, you need to add assertType.

2022-02-01 09:08 UTC, ondrejmirtes commented on tests/PHPStan/Analyser/data/bug-4457.php
> +	}
Also test the #4457 scenario in this file.

2022-02-01 10:27 UTC, staabm commented
after making this return-type more precise we can see that a cross-php-version `version_compare()` check can get complicated, especially when phpstan-strict-types are activated.

any idea how this can be simplified?

2022-02-01 10:28 UTC, staabm commented on resources/functionMap_php80delta.php
> +		'version_compare' => ['-1|0|1|bool', 'version1'=>'string', 'version2'=>'string', 'operator='=>'string'],
I am not sure, should this also include `'operator'=>'string|null'`?

2022-03-17 11:58 UTC, staabm commented
Interessting case https://github.com/composer/composer/commit/dec123770ff1f5bde63f0a4b7ce1b5b627893bf8

2022-06-16 06:49 UTC, closed without merging